### ISSUE TITLE
Origins screen not coming up when creating a new world

### ISSUE THREAD

**Issue by CalaMariGold** [EdwinMindcraft/origins-architectury#10]
Forge 36.1.16

Not sure what information you need, so here's the latest.log

[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/6446281/latest.log)

**Comment by EdwinMindcraft** [comment]
I was unable to reproduce the bug with this mod set:
[https://pastebin.com/2qhqDuZi](https://pastebin.com/2qhqDuZi)
If you have any additional mods, please indicate them, and I will test them, otherwise.
If applicable, consider updating outdated mods (Optifine excluded) as it may solve the issue.

**Comment by Souperhero** [comment]
Additionally, you are un-killable prior to choosing origin. Mobs, fall, and commands cant kill you.  

After choosing origin, you can die normally.

[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/6496182/latest.log)

**Comment by EdwinMindcraft** [comment]
As far as I can tell, this is a ping related issue as I can't reproduce them on a locally hosted server.
This isn't easily fixable but there are some solutions. I'll try one out on the next release.
As for Souperhero's comment, it's intended for Singleplayer to avoid dying during the selection, and the dimension change is a fallback for when mods make you start in another dimension (but it doesn't seem to work that well as Origins seems to override that).
