### ISSUE TITLE
powers that don't specify a sprite for the cooldown bar to use will render as all black

### ISSUE THREAD

**Issue by tovc** [EdwinMindcraft/origins-architectury#108]
`"hud_render":{
     "bar_index":4
  }` 
will render as all black, while
`"hud_render":{
     "bar_index":4,
     "sprite_location": "origins:textures/gui/resource_bar.png"
  }`
will correctly the show the cooldown bar

**Comment by EdwinMindcraft** [comment]
Should be fixed for 1.18

**Comment by tovc** [comment]
seems to be fixed in 1.18.1, only tested it with 1 power tho
