### ISSUE TITLE
origins:add_velocity action inverts one of the axes when using "local" space

### ISSUE THREAD

**Issue by tovc** [EdwinMindcraft/origins-architectury#109]
origins:add_velocity action will invert the added X velocity when adding "Z" (forwards) velocity

adding X velocity seems to be completely broken

Y velocity seems to be added incorrectly occasionally when aiming up/down

**Comment by EdwinMindcraft** [comment]
This was a known issue of both the forge and fabric versions for 1.16.5. 1.17.1 is now discontinued, please update to 1.18.1
