### ISSUE TITLE
Game crash when you die as arachnid 

### ISSUE THREAD

**Issue by RangerSpade** [EdwinMindcraft/origins-architectury#11]
Not sure why but everytime i spawn as arachnid and die the game will crash, happens to my friends too

**Comment by EdwinMindcraft** [comment]
Please attach your crash logs so that I can know which interaction is causing the crash.

**Comment by RangerSpade** [comment]
The craziest thing is, it doesn't load a crash file at all.... it freezes indefinitely until you click on it.. I had it running for over 20 mins and still it just was frozen.
