### ISSUE TITLE
modify_crafting not registered

### ISSUE THREAD

**Issue by keleko34** [EdwinMindcraft/origins-architectury#110]
It looks like the origins:modify_crafting power is not registered.

`Failed to read fields: Unknown registry key: origins:modify_crafting`

**Comment by EdwinMindcraft** [comment]
Origins forge only support powers up to MC1.16.5.

Other have not been, and will not be implemented for MC1.17.
I am in the process of updating Origins to 1.18.1, so this will have to wait.
