### ISSUE TITLE
[1.18.1] Phantom can take damage while inside a solid block when invisible

### ISSUE THREAD

**Issue by DarkSoulMastery** [EdwinMindcraft/origins-architectury#111]
Whenever you go invisible and go inside a block, you began taking damage in the block even if invisible

**Comment by EdwinMindcraft** [comment]
I'm still working on updating origins. The current release is mostly here as something to give people who are willing to play with major issues while I solve ~4000 compilation errors I got from updating upstream.

Also yes current Apoli is compilable, but 5s of play testing gave me some pretty bad results, so there's still quite a bit of work to solve the current issues, plus Origins isn't in line with upstream yet.

**Comment by EdwinMindcraft** [comment]
Fixed in 1.3.1
