### ISSUE TITLE
[1.18.1Optifine issue again] Origins 1.3.1.0 crashes with Optifine. once again...

### ISSUE THREAD

**Issue by DarkSoulMastery** [EdwinMindcraft/origins-architectury#112]
Whenever you play Origins 1.3.1.0 with Optifine, It begins to crash the game even if Optifine crash was fixed for 1.17

**Comment by EdwinMindcraft** [comment]
I have a fix for the next release, but its 10PM and I'm not booting a proper IDE right now.

**Comment by EdwinMindcraft** [comment]
For now I added an artifact to the last release.

**Comment by keleko34** [comment]
![Artifact](https://c.tenor.com/Pas_bgTFBX4AAAAC/harrison-ford-staring.gif)
