### ISSUE TITLE
origins 1.18.1 crafting is not possible

### ISSUE THREAD

**Issue by Samn100** [EdwinMindcraft/origins-architectury#117]
I played origins mod in forge 1.18.1 minecraft and as soon as i get any item to crafting table it disapears and you can't craft anything.

**Comment by PhoenixLife89** [comment]
The same is happening to me. I can collect the materials just fine, but when I put them in the crafting interface, they disappear.

**Comment by jigaming** [comment]
same here is there a fix yet ??
