### ISSUE TITLE
Can’t choose origin on Mohist server

### ISSUE THREAD

**Issue by K9Kr** [EdwinMindcraft/origins-architectury#12]
Hello, I have a problem with this port. I am using Mohist on my server and me and all my friends were all excited when we discovered, that this mod was recently ported to forge. I installed on my server but whenever someone wants to join they cannot choose origin, so I must set them origin manually, and when I restarted minecraft and joined back on a server I had no origin. What can I do with this problem?

My mods are:

![image](https://user-images.githubusercontent.com/81383438/117572231-3c867e80-b0d2-11eb-8f42-c8e9312de8d5.png)

![image](https://user-images.githubusercontent.com/81383438/117572254-59bb4d00-b0d2-11eb-878d-34481c313f89.png)

![image](https://user-images.githubusercontent.com/81383438/117572263-617af180-b0d2-11eb-9d22-d04ad60d8a6c.png)

**Comment by EdwinMindcraft** [comment]
I will be closing this at it is a different version of #10. If you have any additional information, please report it there.
