### ISSUE TITLE
Possible Origins API gradle dependency readme directions?

### ISSUE THREAD

**Issue by keleko34** [EdwinMindcraft/origins-architectury#120]
I am looking to integrate origins api into a project and I am having difficulty integrating origins as a dependency maybe due to the multiple projects and dependencies origins has. I was wondering if in the readme there could be more instructions on this? Or maybe just some helpful direction here on the easiest way to achieve this? Thanks!

**Comment by EdwinMindcraft** [comment]
Right now, I believe the easiest way to do this would be to use a flatDir gradle repository.
I'm not really sure mixins will work, but that's my best guess.

**Comment by keleko34** [comment]
Thanks for pushing the latest to curse, curse maven is much easier way to go :)
