### ISSUE TITLE
[1.18.1] Origins crash with radium whenever I use radium with Optifine

### ISSUE THREAD

**Issue by DarkSoulMastery** [EdwinMindcraft/origins-architectury#121]
The issue is that using radium and origins with optifine can crash the game, when I remove optifine from the jar and keep radium, it works, while removing radium can fix the crash problem

**Comment by DarkSoulMastery** [comment]
I found the reason from fabric version why phantom take damage with lithium/radium https://github.com/apace100/origins-fabric/issues/473

**Comment by EdwinMindcraft** [comment]
Should be fixed in 1.3.1.8

**Comment by DarkSoulMastery** [comment]
Fixed, however, you can take damage inside walls as a phantom with radium in use because of https://github.com/apace100/origins-fabric/issues/473

**Comment by EdwinMindcraft** [comment]
The same fix works, just in radium.properties.
