### ISSUE TITLE
[1.18.1] Java Error: Caused by: java.lang.ClassCastException

### ISSUE THREAD

**Issue by killinmesmols** [EdwinMindcraft/origins-architectury#124]
Hi, I always get the same error message when I attempt to use certain origins such as Phantom or Enderian, but not others like Feline or Arachnid. I get an internal error message on my server. All origins work fine on single player, not sure what the issue is. 
How does this come about?

[ Here's the log](https://gist.github.com/killinmesmols/9faf2710e2e65aca099773b59ba383ac)

**Comment by EdwinMindcraft** [comment]
Fixed in .9
