### ISSUE TITLE
Crash using some power of origins datapack

### ISSUE THREAD

**Issue by Foxsyl** [EdwinMindcraft/origins-architectury#128]
Minecraft Version 1.18.1
Origin Version 1.3.11
Datapack used :  GiantOrigin

this crash is poping when i use slam power for primiary key,  and if i am in air i falll fast and make explosion but crash is before explosion in mid air

if i join many time i have crash but a few more and i hear explosion and then i can join normally

code of power that make crash:
{
	"type": "origins:multiple",
	"name": "Colossal Slam",
	"description": "You can slam into the ground, creating a small explosion",
	"resource": {
		"type": "origins:resource",
		"min": 0,
		"max": 1,
		"hud_render": {
			"should_render": false
		}
	},
	"down": {
		"type": "origins:active_self",
		"hidden": true,
		"key": {
			"key": "key.origins.primary_active"
		},
		"cooldown": 900,
		"hud_render": {
			"sprite_location": "origins:textures/gui/community/spiderkolo/resource_bar_02.png",
			"bar_index": 2
		},
		"condition": {
			"type": "origins:on_block",
			"inverted": true,
			"block_condition": {
				"type": "origins:movement_blocking"
			}
		},
		"entity_action": {
			"type": "origins:and",
			"actions": [
			{
				"type": "origins:add_velocity",
				"y": -0.67
			},
			{
				"type": "origins:change_resource",
				"resource": "giantorigin:slam_resource",
				"change": 1
			},
			{
				"type": "origins:passenger_action",
				"action": {
					"type": "origins:dismount"
				}
			}
			]
		}
	},
	"damage": {
		"type": "origins:action_on_land",
		"condition": {
			"type": "origins:resource",
			"resource": "giantorigin:slam_resource",
			"comparison": "==",
			"compare_to": 1
		},
		"entity_action": {
			"type": "origins:and",
			"actions": [
			{
				"type": "origins:change_resource",
				"resource": "giantorigin:slam_resource",
				"change": -1
			},
			{
				"type": "origins:explode",
				"power": 2,
				"damage_self": false,
				"indestructible": {
					"type": "origins:or",
					"conditions": [
					{
						"type": "origins:block",
						"block": "minecraft:chest"
					},
					{
						"type": "origins:block",
						"block": "minecraft:barrel"
					},
					{
						"type": "origins:block",
						"block": "minecraft:cobweb"
					},
					{
						"type": "origins:block",
						"block": "minecraft:spawner"
					}
					]
				}
			}
			]
		}
	}
}
Crash on website for better view : https://crashy.net/jrcAgeAaabxpYkctM4FM

and if this not wotk here is .txt
[crash-2022-03-30_11.14.02-client.txt](https://github.com/EdwinMindcraft/origins-architectury/files/8379090/crash-2022-03-30_11.14.02-client.txt)

and more origins have problem like vampire that have blood bar and you need drink sneaking and right click on living entity

**Comment by Foxsyl** [comment]
I dont use other mods only origins

**Comment by EdwinMindcraft** [comment]
Should be fixed in .12
