### ISSUE TITLE
1.18.2 (Phantoms take damage when phasing through blocks)

### ISSUE THREAD

**Issue by Inonedn** [EdwinMindcraft/origins-architectury#129]
when entering spectral mode, you will take damage while inside blocks

**Comment by EdwinMindcraft** [comment]
If you're using radium, see here: https://github.com/apace100/origins-fabric/issues/473

**Comment by Inonedn** [comment]
I am not using radium, but I am using Phekui

**Comment by DarkSoulMastery** [comment]
I got the same issue without using radium, any solid blocks can cause damage

**Comment by EdwinMindcraft** [comment]
No it's another issue.
I've got a fix in a version. I just don't know if it's published.

**Comment by Unknown69** [comment]
Is there any way to fix this? using radium and mixin.entity.collisions.suffocation=false
