### ISSUE TITLE
Prevent Item Use powers prevent using an item on blocks

### ISSUE THREAD

**Issue by apace100** [EdwinMindcraft/origins-architectury#13]
With a `prevent_item_use` power, the items also can't be used on blocks. This is different from the Fabric version, in which only the actual item usage is prevented.

This becomes visible for example with the Arachnid's "Carnivore" power, which uses `prevent_item_use` to stop players from eating carrots and other vegetables. In the Fabric version, they are still able to plant carrots, whereas in this version they can neither eat nor plant them.

Edit: I believe the same applies to entity interactions - e.g. an Arachnid is not able to feed pigs in this version, while they would be able to do that in the Fabric version of Origins.

**Comment by Sylveadiff** [comment]
I am still having this issue as of  0.7.1.4
