### ISSUE TITLE
I have question or this is issue  i cant find config to move resorce bar i have other mods that add wather and its overlaping

### ISSUE THREAD

**Issue by Foxsyl** [EdwinMindcraft/origins-architectury#130]
i use survive mods
![obraz_2022-03-30_174724](https://user-images.githubusercontent.com/101817446/160876653-a6f22003-db73-4df0-83bc-a3562d473cd5.png)

**Comment by EdwinMindcraft** [comment]
Either use configured or just bump it in config/apoli_client.toml

**Comment by Foxsyl** [comment]
ok i find now thanks
