### ISSUE TITLE
1.18.2 Massive lagspikes when placing/breaking blocks in Semi/Full Block chunkloading

### ISSUE THREAD

**Issue by Inonedn** [EdwinMindcraft/origins-architectury#131]
This doesn't happen when the mod isn't installed, but it does when it is installed

[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/8382195/latest.log)

**Comment by RaymondBlaze** [comment]
I assume it has to do with the inefficient [ChunkRendererRegionMixin](https://github.com/EdwinMindcraft/apoli/blob/1.18.x/forge/src/main/java/io/github/apace100/apoli/mixin/ChunkRendererRegionMixin.java) inherited from the fabric version. 
And here is the fabric version of this issue: [ChunkRendererRegionMixin is incredibly inefficent](https://github.com/apace100/apoli/issues/25).

The mixin checks for **every** block in **every** region when they're rebuilt for rendering (in your case it's on placing and breaking blocks, known as block update). I can't come up with an possible solution besides adding a client config and mark the function as inactive by default.

**Comment by EdwinMindcraft** [comment]
There is one, a per-section cache of the status for each client, only updating when necessary.
Plus switching to the new blockstate access type, which would speed things up slightly.
Problem with the prior solution is a huge memory overhead, problem with that latter is a that it won't be nearly enough to do anything.

Also thanks, because I couldn't figure out what the issue was.

**Comment by redeven** [comment]
I wonder if this part of the same issue I've been experiencing. 

Not only by moving but also just looking around in place, my CPU usage spikes to 100% all threads (on a 5900x 24-thread) for as long as I keep moving/looking around, and maybe one more second after letting go. Issue stops when I remove the mod.

**Comment by EdwinMindcraft** [comment]
Closing this the status should be addressed in #164

**Comment by Inonedn** [comment]
I read the email. Thank you
