### ISSUE TITLE
sans datapack doesnt work

### ISSUE THREAD

**Issue by Urwelc0me** [EdwinMindcraft/origins-architectury#133]
the sans origin made by slayerdev doesnt for this mod 1.16.5

[slayerdev](https://www.youtube.com/channel/UC0fzsQvAYukUuOTvWUiaiVw) creator's vid
https://www.mediafire.com/file/5i1pwjy27wjy92c/Sans+V2+(unzip+me!).zip/file download link

**Comment by EdwinMindcraft** [comment]
The pack is designed for 1.17+. Massive amounts of content were added in 1.17 and 1.18 in origins. The pack cannot work for 1.16.
