### ISSUE TITLE
NO RESPAWN

### ISSUE THREAD

**Issue by tmanfoo1** [EdwinMindcraft/origins-architectury#136]
{
    "type": "origins:prevent_sleep",
    "message": "You don't feel tired",
    "name":"Insomnia",
    "description":"You can't ever seem to fall asleep"
}
Insomnia does not allow you to set your spawn point ever.

**Comment by EdwinMindcraft** [comment]
Expected behaviour. If you want to allow set spawn, use `"set_spawn_point": "true"`
[Origins Wiki](https://origins.readthedocs.io/en/latest/types/power_types/prevent_sleep/)
