### ISSUE TITLE
If i use survive mod in server i can't join and i have this error

### ISSUE THREAD

**Issue by Foxsyl** [EdwinMindcraft/origins-architectury#139]
![image](https://user-images.githubusercontent.com/101817446/161322234-4ae1e01c-a726-4e26-9cc7-933f04811abc.png)

**Comment by EdwinMindcraft** [comment]
Install survive on your client

**Comment by Foxsyl** [comment]
i have on client only i can join to server when i disable temperature

**Comment by Foxsyl** [comment]
Survive have something that connect with origins and default is blazeborn immunity to temperature and I think something is not working with this because I try delete this name of origins in survive config and leave blank but it won't help
