### ISSUE TITLE
Datapack not working

### ISSUE THREAD

**Issue by LukeHarbor** [EdwinMindcraft/origins-architectury#141]
The fae / fairy datapack doesn't work.

**Comment by tmanfoo1** [comment]
Try including the data pack or a link to it and the error log! That might help! Also I have a fairy in my bucolic origins mod and she works ;)

**Comment by EdwinMindcraft** [comment]
What they said. Right now I can't debug that because I don't know what datapack you're using.

**Comment by EdwinMindcraft** [comment]
Closed due to lack of information.
