### ISSUE TITLE
GUI wont appear on world creation.

### ISSUE THREAD

**Issue by Z3R0Presence** [EdwinMindcraft/origins-architectury#142]
Hi, i have been trying to put some mods together for a playthrough for myself and friends, and while previously the gui would open, it will not open anymore. i am still in the midst of trying to reduce errors and this is apparent for myself :) The main evidence i can think may help would be, [17:21:03] [Render thread/ERROR]: Adding duplicate value 'Origin(origins:empty)[]' to registry. However, when i am ingame and i run the command to open the gui manually it works and the origins appear and work fine. I have added the latest log i have for this issue:
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/8411485/latest.log)

**Comment by Skulgan** [comment]
I see this issues has been closed. Can you please tell me what your solution was to this issue? I'm experiencing the same problem.
