### ISSUE TITLE
[1.16.5] Curseforge page does not list Cloth Config API as a requirement

### ISSUE THREAD

**Issue by gopgop9000** [EdwinMindcraft/origins-architectury#143]
I added some of the origins mods to an All The Mods 6 server and it crashed on startup due to not having Cloth Config API installed. 
Don't know what else to say other than that but here is the crash log.
[crash-2022-04-04_16.59.56-fml.txt](https://github.com/EdwinMindcraft/origins-architectury/files/8413854/crash-2022-04-04_16.59.56-fml.txt)

**Comment by gopgop9000** [comment]
It seems to load fine when loading singleplayer, however not when adding it to the server.

**Comment by EdwinMindcraft** [comment]
Use the dependencies for the version you have installed. Cloth config was only removed for 1.18

**Comment by gopgop9000** [comment]
It does not have it listed at all anywhere, not in Related nor next to the version number.
![image](https://user-images.githubusercontent.com/22566921/161684953-623db0f9-d36b-4d55-8c42-713b949f1b47.png)
![image](https://user-images.githubusercontent.com/22566921/161685018-172ddacc-0395-4a12-8522-43634964ae90.png)

**Comment by EdwinMindcraft** [comment]
https://www.curseforge.com/minecraft/mc-mods/origins-forge/files/3426062

**Comment by gopgop9000** [comment]
My bad then.
