### ISSUE TITLE
Unable to take damage with DND races datapack installed

### ISSUE THREAD

**Issue by Dankleberg** [EdwinMindcraft/origins-architectury#144]
Playing the game with this datapack makes the player immune to all types of damage (mob, falling, drowning, explosions) except the /kill command and falling into the void.  It does not depend on the race the player chooses, including human.  

Steps to replicate:
1. Start the world with data pack in the datapacks folder
2. Choose race

I replicated it in a pack with just the origins and caelus libraries, as well as with both versions of Pehkui available for 1.18.1 installed on top of that and the issue was consistent with all three variations.

Datapack:
[dnd_origins_v1.2.zip](https://github.com/EdwinMindcraft/origins-architectury/files/8422556/dnd_origins_v1.2.zip)

Mod List:
caelus-forge-1.18.1-3.0.0.2.jar
Origins-1.18.1-1.3.1.12-unified.jar

**Comment by Dankleberg** [comment]
After further messing around with the datapack, it seems that it is due to having to suborigins.  Basically any time you don't go through menus for each layer, I think it still thinks you are choosing and gives you the invincibility you normally have when you haven't picked an origin yet.

**Comment by EdwinMindcraft** [comment]
It's something else.
I'm working on a fix.
