### ISSUE TITLE
Mixin error on 1.18.2

### ISSUE THREAD

**Issue by keleko34** [EdwinMindcraft/origins-architectury#146]
Updating my modding environment today and the origins mixin is throwing an error.
Forge: 1.18.2 - 40.0.32
Origins: 1.3.1.12
Mixin: 0.8.5

**Error**
```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector isSubmergedInProxy(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/tags/Tag;)Z in origins.mixins.json:WaterBreathingMixin$UpdateAir failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap origins.refmap.json
```

Any ideas? :)

**Comment by keleko34** [comment]
When I try to use the 1.18.2 unified jar instead of Curse Maven I get a different mixin error

```
Mixin apply failed apoli.mixins.json:PlayerEntityMixin -> net.minecraft.world.entity.player.Player: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method m_6469_ in apoli.mixins.json:PlayerEntityMixin was not located in the target class net.minecraft.world.entity.player.Player. Using refmap apoli.refmap.json
```

**Comment by EdwinMindcraft** [comment]
For cursemaven, you may need to disable refmaps.
Also I may or may not have forgotten to check origins' mixins. That's my bad.

**Comment by keleko34** [comment]
> For cursemaven, you may need to disable refmaps. Also I may or may not have forgotten to check origins' mixins. That's my bad.

Thanks for the response, I will try that!

**Comment by EdwinMindcraft** [comment]
It still wont work right now, I can tell you that `isSubmergedInProxy(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/tags/Tag;)Z` is not a correct signature for 1.18.2.

**Comment by EdwinMindcraft** [comment]
Nevermind, the refmaps are good for 1.18.2, you just need to disable them if you're not using Arch loom.

**Comment by keleko34** [comment]
I am actually using architectury as a dependency in my project. I disabled the refmaps but the same errors popped up for both maven and the unified jar file with only one difference. `No refmaps loaded` was the text at the end of the error instead of `Using refmap [origin/apoli].refmap.json`
I updated to your newest 13 version but issue persists it is just with 1.18.2, if I go back to 1.18.1 there is no issue on those versions. Sadly I am also integrating with the FTB mods and they do not even have a stable 1.18.1 version for their mods.

**Comment by keleko34** [comment]
latest 1.18.2-1.3.1.14 unified jar
```
Mixin apply failed apoli.mixins.json:PlayerEntityMixin -> net.minecraft.world.entity.player.Player: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method m_6469_ in apoli.mixins.json:PlayerEntityMixin was not located in 
the target class net.minecraft.world.entity.player.Player. Using refmap apoli.refmap.json
```

**Comment by EdwinMindcraft** [comment]
I forgot the joys of shadow...
If you're using mojmaps, you can try to disable the reobf step of the compilation process, that could work, but for some reason, shadows aren't in the refmap and just renamed flat out.
I had the opposite problem when building 1.18.2 releases and I fixed it by reobfuscating before shadowing.

**Comment by keleko34** [comment]
> I forgot the joys of shadow... If you're using mojmaps, you can try to disable the reobf step of the compilation process, that could work, but for some reason, shadows aren't in the refmap and just renamed flat out. I had the opposite problem when building 1.18.2 releases and I fixed it by reobfuscating before shadowing.

hmm.. I was using the same setup as you actually with parchment, same versions n all. I will try swapping to the official and then turn off reobf

**Comment by EdwinMindcraft** [comment]
Mojmap and parchment are basically the same

**Comment by keleko34** [comment]
I could very well be doing something wrong also, here is a quick pastebin of my build gradle [https://pastebin.com/bDUAsRRe](https://pastebin.com/bDUAsRRe)

**Comment by EdwinMindcraft** [comment]
Use fg.deobf on the file, and when using cursemaven, make sure to use the 1.18.2 version. (.14's id would be 3747134)

**Comment by keleko34** [comment]
Thanks mate!!! I was able to get it working. was me after all, sorry for the trouble :)
