### ISSUE TITLE
mod not working on 1.18.1

### ISSUE THREAD

**Issue by HahafunnymanXD** [EdwinMindcraft/origins-architectury#147]
When i checked the datapacks thingy where they're listed it just said it was incompatible "made for an older version of minecraft" and i haven't found a way to remedy this issue.

**Comment by EdwinMindcraft** [comment]
That's vanilla behavior. You can still use the datapack.
[For more info](https://minecraft.fandom.com/wiki/Pack_format)

**Comment by HahafunnymanXD** [comment]
yeah the actual issue i was having fixed itself overnight, dunno what happened, (could also just have been something with curseforge i dunno) thanks. (apparently i was too tired to describe the issue proberly so just for clarification it just wouldn't prompt me with the origin selection screen.) Alright so it turns out the issue originates with the "Bucolic Origins" mod.
