### ISSUE TITLE
[1.18.2] Trapdoors do not stop phantoms from being lit on fire due to exposure to sky

### ISSUE THREAD

**Issue by StormCircuit** [EdwinMindcraft/origins-architectury#149]
Just as the title says. Tried Origins 1.3.1.13 on Forge 1.18.2. Made a stone platform, punched a hole, put tinted glass down in said hole and took no fire damage when standing underneath. Replaced the glass with a spruce trapdoor and I began taking fire damage. Tested with no other mods installed.

**Comment by EdwinMindcraft** [comment]
Works as intended, trapdoors aren't solid blocks, even if some variants aren't see-trough.
