### ISSUE TITLE
Trying to play as a merling does not set your spawn in the ocean

### ISSUE THREAD

**Issue by NathanYumekoe** [EdwinMindcraft/origins-architectury#15]
As per title, when selecting a merling you do not spawn in the ocean as per the fabric mod, but instead spawn in the regular spawnpoint.

**Comment by EdwinMindcraft** [comment]
That's because the Merling origin has the ocean spawn in neither this nor the fabric mod.
Check the datapacks you are using on fabric, if merling spawn doesn't work with those datapacks, reopen this issue.
