### ISSUE TITLE
Custom Datapack not working

### ISSUE THREAD

**Issue by VirenRunner** [EdwinMindcraft/origins-architectury#152]
I made a custom datapack origins where i can unlock abilities but its not working. when i unlock the skill and use it nothing happens i need help. is it the way i coded it or is it the mod itself. the ability i made is give player an item when pressing primary+shift but nothing happens. any ideas? although it only works for fabric not forge. so what is going on?

Here's the data pack I made
[pixsoulist.zip](https://github.com/EdwinMindcraft/origins-architectury/files/8468334/pixsoulist.zip)

**Comment by EdwinMindcraft** [comment]
Should work in the latest versions
