### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by seanxiecn** [EdwinMindcraft/origins-architectury#155]
Sometimes when I enter the world I have to choose the origin again. This also happens during the gameplay, when the tps suddenly boosts or after respawning from death, pressing the 'o' for origin gui which displays "you can not have any origin". The bug have existed for a long time, Can you fix it?

**Comment by EdwinMindcraft** [comment]
Please state the version of the mod you are using, as well as the minecraft version. Please note that 1.16.5 is currently not supported.
