### ISSUE TITLE
Strange Datapack Origin Layer Behavior

### ISSUE THREAD

**Issue by smbanasik** [EdwinMindcraft/origins-architectury#162]
MC Version: 1.18.2
Origins Version: Origins-1.18.2-1.4.1.0-unified
Forge Version: 40.1.0

Hello! I have been attempting to make a custom origin and add it to default layer with the rest of the origins. However, after following the origins docs, the custom origin is placed into it's own layer first, and the other origins are selectable in a separate one. This is the most common and recent outcome. I'm using KubeJS to hold the datapack.

Other outcomes that I've experienced: Orb of origin not bringing up a menu, only the custom origin being selectable, the game refusing to start due to datapack issues.

When it didn't start I looked at the debug log and it showed an error with the PartialGuiTitle merge function receiving a null value, though I did not save the log so I am unable to give more information besides that.

**EDIT**: The behavior was cause by a misspelling, however now the datapack is preventing the world from loading again, and I have error which is attached below, the error is in the bottom of the text. It seems that the PartialGuiTitle merge function recieves a null value from the PartialLayer title.

[debug.log](https://github.com/EdwinMindcraft/origins-architectury/files/8527235/debug.log)

**Comment by RaymondBlaze** [comment]
In [PartialLayer#L57](https://github.com/EdwinMindcraft/origins-architectury/blob/1.18.x/1.18.2/src/main/java/io/github/edwinmindcraft/origins/api/data/PartialLayer.java#L57), the titles are merged uncheck.
Should check if `this.title()` is null and check in the `PartialGuiTitle#merge` if the param PartialGuiTitle is null.
