### ISSUE TITLE
apocalypse origins fails to validate when loaded as a datapack

### ISSUE THREAD

**Issue by lag42** [EdwinMindcraft/origins-architectury#163]
using the method [apocalypse origins](https://www.curseforge.com/minecraft/mc-mods/apocalypse-origins#c322) describes on it's page to extract the datapack that contains the actual functionality for use with forge, it fails to validate preventing creating a world while it's loaded

using:
minecraft 1.18.2

forge 40.1.0

apocalypse origins 0.1.97

origins (forge) 1.18.2-1.4.1.0

caelus API 1.18.1-3.0.0.2

[link to log](https://gist.github.com/lag42/10c1d491c0588ae1cdb1cb77b645c47e)

**Comment by EdwinMindcraft** [comment]
Update origins

**Comment by lag42** [comment]
my bad entirely, i did not see the update 2 hours ago that fixes this exact issue
