### ISSUE TITLE
Inconsistency with Fabric version: Merling vision.

### ISSUE THREAD

**Issue by KingEdward9830** [EdwinMindcraft/origins-architectury#170]
So in the Fabric version, Merling vision also acts as night vision, so while it's toggled on and you're underwater you can see perfectly even underground. In this version, while the toggle still does remove the "fog" effect applied by being underwater, it does nothing to help with night vision. This makes early game mining a real PITA on this version since you can't use torches underwater xD EDIT: Origins 1.18.2-1.4.1.1-unified.jar, Forge 40.1.0, Minecraft 1.18.2, Caelus forge-1.18.1-3.0.0.2.jar EDIT2: And before you ask, yes I tested with no other mods :)

**Comment by EdwinMindcraft** [comment]
Related to #175. Closing as duplicate
