### ISSUE TITLE
Origins Mod failing to launch on Forge 40.1.14

### ISSUE THREAD

**Issue by bixyfroot** [EdwinMindcraft/origins-architectury#172]
Error Message:
This crash may be caused by an invalid Java runtime configuration. Check any custom configuration settings. Exit Code: 1

Replication:
1. Run CurseForge launcher
2. Install Origins (Forge) -.18.2-1.4.1.1 and Pehkui-3.30+1.18.2 on Forge 40.1.14
3. Play profile

Origins on latest version of Forge 40.1.14 is causing error on launch but it works fine on Forge 40.1.0 (have played it in 40.1.0 and it works great, no crashes). No other mods were installed as I was making a small modpack and isolated the issue to Origins or Pehkui

**Comment by EdwinMindcraft** [comment]
Can you try with forge 40.1.15? 40.1.3 >> 40.1.14 have a binary breaking change that was reverted in .15.

**Comment by EdwinMindcraft** [comment]
Tested it. Pehkui is broken, origins works fine with 40.1.16. Closing this as it isn't an origins issue. (The bug still exists even without oirigins).
