### ISSUE TITLE
Mixin Error while building addon

### ISSUE THREAD

**Issue by googlepox** [EdwinMindcraft/origins-architectury#173]
Hello,

I have a dev environment setup using forge 40.1.15 and origins 1.4.1.1 and I'm getting a mixin error regarding the NoCobwebSlowdownMixin. What am I doing wrong?

[latest.log](https://pastebin.com/wSwmwjYQ)

[build.gradle](https://pastebin.com/qHHh1DRg)

**Comment by EdwinMindcraft** [comment]
I don't really know. You may want to add [MixinGradle](https://github.com/SpongePowered/MixinGradle) (plugin) as well as the mixin AP (dependency) and try with that:

```gradle
annotationProcessor "org.spongepowered:mixin:0.8.5:processor"
testAnnotationProcessor "org.spongepowered:mixin0.8.5}:processor"
```

**Comment by googlepox** [comment]
Tried that, still getting the same error. Here's the rest of the error that wasn't in the latest.log
https://pastebin.com/9NchtvC3

**Comment by EdwinMindcraft** [comment]
Try downgrading to forge 40.1.0 for now, apparently they broke something, I don't know what. I'll won't be able to investigate right now.

**Comment by googlepox** [comment]
That worked, thanks!
