### ISSUE TITLE
Elytra Power Texture - What is the syntax?

### ISSUE THREAD

**Issue by MayliSong** [EdwinMindcraft/origins-architectury#174]
I'm sorry to make this an issue but I've been banging my head against a wall for nearly a month trying to figure this out now. When using a datapack to add the elytra flight power to an origin, you are supposed to be able to tell it what texture to render with.
``` {
"type": "origins:elytra_flight",
"render_elytra": true,
"texture_location": "minecraft:textures/entity/elytra.png"
```
I cannot for the life of my get it to direct to any other texture without it telling me the specified file doesn't exist with a "failed to load texture, file not found" error. I've tried loading it from within the datapack in almost every folder structure I can think of, tried loading it from a texture pack in several different folder structures, no luck.

I made a pastebin with the most recent iteration of the error, in case it's actually an issue and not me messing up the file syntax. I know this might not count as a proper issue but I am getting desperate. [Pastebin here](https://pastebin.com/gnPS40uB) of the Failed to Load Texture error. This one was trying to put it in a texture pack and load from the specified location the same way you would a default texture, but its been the same error every time as far as I can tell, no matter where I put it/what I try.

**Comment by EdwinMindcraft** [comment]
The texture needs to be in a resource pack, using assets/&lt;namespace&gt;/&lt;path&gt;
In the case of your log, that would be `assets/minecraft/textures/entity/phoenixelytra.png`

**Comment by MayliSong** [comment]
So, I was pretty sure I'd tried it as that before, but I tried it again just to be sure, literally copying the file path you gave me there, and it is giving the same error. 

`[15:39:50] [Render thread/WARN]: Failed to load texture: minecraft:assets/minecraft/textures/entity/phoenix_elytra.png
java.io.FileNotFoundException: minecraft:assets/minecraft/textures/entity/phoenix_elytra.png`

The texture is called `phoenix_elytra.png` and is located in a resource pack following exactly that file path. I also tried it on a private server a friend lent me with a required server texture pack for good measure and got the same error. I have now tried disabling any mods I had that I thought might have been messing with the rendering of the player (3dSkinLayers, Ears, and Optifine) and no luck. I plan to continue disabling mods to see if any of them are causing this.

**Comment by EdwinMindcraft** [comment]
Sorry, the associated path would've been `assets/minecraft/textures/entity/phoenix_elytra.png` for the location `minecraft:textures/entity/phoenix_elytra.png`

In the case of raw textures the asset path is `assets/<namespace>/<path>` for the location `<namespace>:<path>`

**Comment by MayliSong** [comment]
I was _so_ sure I had tried that syntax too but apparently not. Seriously, _THANK YOU_, I've been tearing my hair out over this for ages
