### ISSUE TITLE
Payload larger than 1048576

### ISSUE THREAD

**Issue by iMythJj** [EdwinMindcraft/origins-architectury#179]
I am playing with a datapack/mod with less than 10 origins. It works fine on singleplayer, but once we put it in our server. Upon attempting to connect we get this message.

"Failed to connect to the server

Internal Exception:
io.netty.handler.codec.DecoderException:
java.lang.IllegalArgumentException: Payload may not be larger than 1048576 bytes"

**Comment by BkBaller404** [comment]
Minecraft has a packet size limit and Origins sends a lot of LARGE packets. Try this mod to see if it resolves your issue. 
https://www.curseforge.com/minecraft/mc-mods/connectivity

____
!BAMF!
