### ISSUE TITLE
[Discussion/Suggestion] Compatability with Diet mod and ability to disable food restrictions in general.

### ISSUE THREAD

**Issue by Lgmrszd** [EdwinMindcraft/origins-architectury#18]
[Diet](https://www.curseforge.com/minecraft/mc-mods/diet) mod is designed to give players benefits of having various diet. Unfortunately, this doesn't play nicely with Origins, as some origins have limited diet.

Possible solution (as discussed with Diet's developer) is to add option to Diet mod to have origin condition for Dietary effects (example, don't give negative effects for having low value for Fruits and Vegetables food groups, and instead give negative effects if those values pass certain threshold).
If this feature gets implemented, the only problem remaining is to disable Origins' food check. While it may be possible by overriding powers through datapack or removing origin-related tags from food (or add "#origin:ignore_diet" tag for all foods), I want to know if it is possible to disable this check automatically if Diet mod is installed. Also, you can suggest other approach for mod integration.

**Comment by EdwinMindcraft** [comment]
Added a config option that defaults to true if Diet is loaded to disable food restrictions.

**Comment by EdwinMindcraft** [comment]
I should point out that I am sorry if you installed 0.7.1.4 as disableFoodRestrictions was doing the exact opposite as what it was supposed to do. It's fixed now.
