### ISSUE TITLE
Does not track fall damage

### ISSUE THREAD

**Issue by SergGrey** [EdwinMindcraft/origins-architectury#181]
Versions
Minecraft: 1.18.2
Forge: 40.1.20
Origins: Origins-1.18.2-1.4.1.1-unified

I'm trying to reduce fall damage, but tests have shown that damage from "fall" is not tracked. I removed the condition for the name of the damage and everything worked.
```
{
	"name": "Elven Elegance",
	"description": "You take 75% less fall damage",
	"type": "origins:modify_damage_taken",
	"damage_condition": {
		"type": "origins:name",
		"name": "fall"
	},
	"modifier": {
		"operation": "multiply_total",
		"value": -0.75
	}
}
```

**Comment by EdwinMindcraft** [comment]
It should've been fixed with 1.4.1.4.
