### ISSUE TITLE
Sometimes unable to view origin details on forge.

### ISSUE THREAD

**Issue by Angular-Angel** [EdwinMindcraft/origins-architectury#185]
So I have a ton of mods installed, including Origins, and sometimes when I press o to view my origins, it says I cannot have any origins - but, when I check via the '/origin get' command, it tells me I have origins, and their powers work and everything. If I change my origin, sometimes this problem persists, and sometimes it goes away and lets me view my origin details again. I've been switching up my mods a bunch, including adding origins classes and a datapack for randomizing origins on death or by choice when sleeping, and the bug has persisted throughout this.

**Comment by EdwinMindcraft** [comment]
Fixed in 1.4.1.3
