### ISSUE TITLE
[1.18.2] Elytrian crash when opening inventory with Survive installed

### ISSUE THREAD

**Issue by KarsKarze** [EdwinMindcraft/origins-architectury#186]
When playing with the Survive mod, the game crashes when I open the creative inventory as elytrian (or any origin with armour restrictions for example fae and elf from medieval origins/collection of singiro).
With more mods installed, it would happen in survival as well. I couldn't pin point which mod causes that, but removing survive fixes the problem in both instances.

Steps to reproduce:

   1. Install Origins alongside Survive
   2. Open a creative world
   3. Choose Elytrian
   4. Open Inventory
   5. Game crashes
  

Crash report and logs attached.

[crash-2022-06-03_11.30.05-client.txt](https://github.com/EdwinMindcraft/origins-architectury/files/8828874/crash-2022-06-03_11.30.05-client.txt)

[debug.log](https://github.com/EdwinMindcraft/origins-architectury/files/8828875/debug.log)

[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/8828876/latest.log)

**Comment by MisterGrace** [comment]
Similar issue here. 
Using AQM3, If i right click any item while being Elytrian The game has started to crash as it detects if the Equipment i'm wearing is restricted or not. If i wear base Minecraft gear no issue. But lets say i put on a pickaxe in my offhand that's from a different mod and try to eat food. Crash, The rings from Goblins and Dungeons, i cannot right click to "equip" or to move to offhand. It will crash. If i have the Goblin Crown on head and right click, same thing crash. 

I can open up inventory, sometimes it will crash when i move things to my inventory. But it definitely is an issue that comes out of no where with other mods that may not have an armor power level, just a buff while in use. Like those rings that must be in offhand, or the crown that has no armor value listed, Doesn't even say 0 armor, just that it reduces the vision of goblins around you and weakens them.



[crash 6-3-22 936.txt](https://github.com/EdwinMindcraft/origins-architectury/files/8838330/crash.6-3-22.936.txt)

[server side LOG  6-3-22 952.txt](https://github.com/EdwinMindcraft/origins-architectury/files/8838331/server.side.LOG.6-3-22.952.txt)
