### ISSUE TITLE
Advancement condition not working on forge version.

### ISSUE THREAD

**Issue by MorrisMo333** [EdwinMindcraft/origins-architectury#187]
I tried making a origin ability with an advancement condition on this version of the mod but found out that that condition seemingly only worked when using the fabric version of origin. Specifically in my log it said that: 
{
    "type": "origins:advancement",
    "advancement": "minecraft:story/smelt_iron"
  }
isn´t a json array. 
I specifically used the Origins-1.18.2-1.4.1.1-unified.jar file and version of forge origins.

**Comment by HoodBlah** [comment]
Conditions are very bugged with this mod. Even normal conditions like resource bar conditions don't work.
