### ISSUE TITLE
Apoli giving several error messages on join attempt [MULTIPLAYER MODPACK]

### ISSUE THREAD

**Issue by Ampersand20** [EdwinMindcraft/origins-architectury#190]
Apoli gives this error message when I try to join the server.
![image](https://user-images.githubusercontent.com/96956366/174446871-087dec8b-7692-4148-9243-a28e826e31cd.png)

I have ensured that everything is the correct version (1.18.2). It seems to me that Apoli is the only mod at fault but since this is a forge issue I figured here would be better to ask.

**Comment by EdwinMindcraft** [comment]
I'm going to assume this is like #191. If it's not please link your datapacks and/or modlist.
