### ISSUE TITLE
Origins Forge v1.18.2-1.4.1.2 - Causing Datapack Errors / Server Crash

### ISSUE THREAD

**Issue by AetheriMC** [EdwinMindcraft/origins-architectury#191]
Issue: 

The most recent update of Origins is causing server crashes with the following warning - _Failed to load datapacks_.

[debug.log](https://github.com/EdwinMindcraft/origins-architectury/files/8933980/debug.log)
 
I assumed that since the errors only began after updating Origins, and because datapacks are the means with which we build custom origins, that the datapack error actually meant that the server was finding issues with the way a power or origin had been coded. Following through with this, I began testing our datapack from a list of 100+ powers and a dozen origins, slowly reintroducing items back into the server and restarting it until I managed to locate what was causing the crash. I found two powers that I believe are the culprits. 

The first power is Growth, which simply produces a bonemeal effect around the caster. The second power, Change Weather, is slightly more complicated but in a fairly straightforward way, it detects the status of the weather on the server and updates it accordingly. Both powers are custom but worked without issue with the previous version of origins we were using, which was v1.4.1.1. Unfortunately, I haven't been able to identify anything within the code for these powers that immediately stands out as needing to be fixed, especially since they both worked fine before the change.

Here is the file for Growth:
[growth.txt](https://github.com/EdwinMindcraft/origins-architectury/files/8933988/growth.txt)

Here is the file for Change Weather:
[change_weather.txt](https://github.com/EdwinMindcraft/origins-architectury/files/8933986/change_weather.txt)

If it is a coding error on my end, any help would be much appreciated. Otherwise, I believe that something most likely broke in the update.

Thanks in advance!

**Comment by EdwinMindcraft** [comment]
This is a bug due to a field being wrongfully assigned on my end.
I'm in the process of sanitizing my inputs to figure out where everything went wrong.
