### ISSUE TITLE
Problem between Origin Classes & Pehkui

### ISSUE THREAD

**Issue by bassistracer** [EdwinMindcraft/origins-architectury#192]
MC Version: 1.18.2
Forge Version: 40.1.52
Origins (Forge) Version: 1.4.1.4-pre2
Pehkui Version: 3.3.2
Mod Manager: PolyMC

Add-on races made for Forge forks of Origins can't seem to work quite right with Pehkui. Tried all that were available and all came with the same issue: sizes don't change automatically, and players are left at their base height when selecting that race. 
Pehkui itself works and can change sizes via the console.

**Comment by EdwinMindcraft** [comment]
Could you try with 1.4.1.3/1.4.1.4-pre1 to see if you get similar results?

**Comment by bassistracer** [comment]
> Could you try with 1.4.1.3/1.4.1.4-pre1 to see if you get similar results?

Just tried it with these versions -- the GUI you should see at the beginning wasn't even coming up (when the add-on mods were installed, even as I got older versions of those), but did come up if I forced the GUI open through the console.

1.4.1.3 (and pre-1) seemed to work this way with the latest version of Origins++ for example -- the GUI wouldn't show up first thing on a new world, but the add-on races that grow/shrink you do work when you open the GUI via console and select a race.

Spent like several hours loading and reloading everything so hopefully I checked all possible corners lmao.

**Comment by EdwinMindcraft** [comment]
Welp, found the issue, FYI it's not *just* callback powers. Anything that references actions or conditions is broken.
