### ISSUE TITLE
Problem with blazeborn

### ISSUE THREAD

**Issue by gabgat** [EdwinMindcraft/origins-architectury#193]
If the player choose the blazeborn origin and the nether is disabled in the server, it generates the nether, when and try to tp the player causes the player to crash.

**Comment by EdwinMindcraft** [comment]
Remove the blazeborn's power from your server, it can be done via datapack.
I can't be held liable for the owner deciding that half the game should be missing.

**Comment by gabgat** [comment]
I was thinking about adding a condition for the nether respawn, if the nether is disabled in the properties file or by another mod, also the nether spawning needs to be turned off

**Comment by EdwinMindcraft** [comment]
Yes, it would be feasible, but realistically speaking, this is an extreme edge case that would make the code for that power significantly more complex.

Deactivating the nether is something that is only done in extreme edge cases, and not by 99.9% of the player base.
If someone is willing to disable part of the core experience of the game, they should be willing to do [basic research on the origins wiki](https://origins.readthedocs.io/en/latest/json/origin/) to fix any issues that may arise.
