### ISSUE TITLE
Possible conflict with JourneyMap

### ISSUE THREAD

**Issue by ghost** [EdwinMindcraft/origins-architectury#194]
#### Origins Version:

`origins-classes-forge-1.1.5.1`

#### Forge Version:

`40.1.31`

#### Describe the problem in repeatable steps:

I've been noticing lots of memory lag and log spam from Journeymap when on the Origins selection menu.. could be a possible conflict?
At the start of a world to select their "origin/race" and at that menu jm goes crazy... starts lagging the hell out of the game and spamming the log
that message gets printed, sent thousands of times. Journeymap discord said that the issue is not with them, it's origins, so i posted the issue on both githubs

#### Relevant errors:

https://paste.ee/p/vTLNL

**Comment by EdwinMindcraft** [comment]
I'm going to assume this is either fixed, or not an issue anymore for the same reasons as JM.
