### ISSUE TITLE
crashing when "Right Clicking"

### ISSUE THREAD

**Issue by BlueRebellion** [EdwinMindcraft/origins-architectury#199]
While playing as Fae Origin, using Medieval MC Forge 1.18.2.
The game crashes when right clicking with the "Ring of Health" item, from the Goblins & Dungeons mod, in the offhand/shield slot
[crash-2022-07-13_02.34.09-client.txt](https://github.com/EdwinMindcraft/origins-architectury/files/9100243/crash-2022-07-13_02.34.09-client.txt)
.

**Comment by EdwinMindcraft** [comment]
Update origins.
