### ISSUE TITLE
Incompatibility with Pehkui?

### ISSUE THREAD

**Issue by clootas** [EdwinMindcraft/origins-architectury#2]
[Here's the crash report](https://pastebin.com/sZBtCCbB)

I'm using the [1.16.5] [Forge] Pehkui 2.0.0 version. A few data-packs depend on it to add certain origins. I'm not entirely sure if it's your mod causing it or not, I'm not too good with crash reports.

**Comment by EdwinMindcraft** [comment]
This looks more like an issue from the mod performant. Try disabling it for testing and check if the bug still occurs.

**Comment by clootas** [comment]
That did it, my bad. I do seem to have problems with the data-packs after installing Pehkui but I'm not sure if its a problem on my end or not

**Comment by EdwinMindcraft** [comment]
If you have a specific datapack that causes issues, please write attach the datapack with the issue.

**Comment by clootas** [comment]
Fixed with the latest version, cheers
