### ISSUE TITLE
[1.18.2-1.19][Calio][JarJar] Request for independent Calio release once Origins move to use Forge's JarJar system

### ISSUE THREAD

**Issue by RaymondBlaze** [EdwinMindcraft/origins-architectury#203]
Calio is a great and useful lib, I especially appreciate your Codec implementation on Forge side and is looking forward to use it outside the Origins mod :)
However the old unified jar way doesn't support this kind of usage :(
Now that Forge had finally implemented the JarJar feature on 1.18.x and 1.19.x, I believe it will be nice make Calio (and maybe Apoli?) a independent lib mod and have its own maven release (Jitpack may be a good choice) just like the Fabric version.
Considering 1.18.x is still supported by the community, it would be better if this request also being accepted on 1.18.x ;) (I know asking for 1.18.x update is actually an annoying backport request, sorry for that if you dislike it)

**Comment by EdwinMindcraft** [comment]
The plan is to release with JiJ for 1.19 but subprojects are not currently supported, so I need to make the gradle script manually. 
But yeah, the goal is to use JiJ whenever I get enough time to *peacefully coerce* a system that is absolutely not designed for subprojects into working properly.

**Comment by EdwinMindcraft** [comment]
I'll see if what I can do for 1.18. And I'll at least try to get a release done, but I'll test the build script on my current workspace (i.e. 1.19)

**Comment by RaymondBlaze** [comment]
Thanks for the quick reply :)
Btw I wonder if it's possible to reimplement Calio back to 1.16.x (especially the possibility to keep the Codec stuff)? This is not a request, I may make a fork and try to work it out myself if needed.

**Comment by EdwinMindcraft** [comment]
As far as I'm aware, calio doesn't rely too much on Java 17 features, so you should be good, but some things may need to move around since forge changed a lot from 1.16-1.19

**Comment by EdwinMindcraft** [comment]
If I didn't make a horrible mistake in my PR, and if they are willing to accept it, FG should have the ability to use subprojects with JarJar at some point.

**Comment by EdwinMindcraft** [comment]
JiJ is done for 1.19, you can find the jars in the description of the [latest release](https://github.com/EdwinMindcraft/origins-architectury/releases/tag/1.5.0.2).
You'll probably need to use flatDirs for now, since I can't find artifact renaming anywhere within gradle.
