### ISSUE TITLE
My origins forge 1.19 won't start

### ISSUE THREAD

**Issue by Baelfyr92** [EdwinMindcraft/origins-architectury#205]
when i try to start my minecraft with:caelus-forge-1.19-3.0.0.3 and Origins-1.19-1.5.0.1-unified the game crash with these message:The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

**Comment by Baggytrousers27** [comment]
#204 Lava visibility isn't playing nicely.

**Comment by EdwinMindcraft** [comment]
Fixed
