### ISSUE TITLE
[1.19] Stuck loading after choosing origin.

### ISSUE THREAD

**Issue by Baggytrousers27** [EdwinMindcraft/origins-architectury#206]
Forge 41.0.106
caelus-forge-1.19-3.0.0.3
origins-forge-1.19-1.5.0.2-fatjar

World loads up fine but selecting any origin (Have tried human, enderian and avian) sends up this warning in the output log:
[Server thread/WARN] [io.gi.ap.or.Origins/]: Player Baggytrousers27 tried to choose invalid origin: origins:empty for layer: origins:origin

[debug.log](https://github.com/EdwinMindcraft/origins-architectury/files/9165333/debug.log)

**Comment by EdwinMindcraft** [comment]
Good news, I know how work around this, bad news is that I want to make the system properly, so this will take some time to fix.
Use the origin set command till then.

**Comment by Baggytrousers27** [comment]
Might be an obvious thing but how do you skip the origin select screen?

**Comment by EdwinMindcraft** [comment]
You can't skip it if you haven't selected something. If it's stuck on a dirt screen or darkened screen without any active gui, just press escape.

**Comment by EdwinMindcraft** [comment]
Should be fixed in 1.5.0.3.

**Comment by Baggytrousers27** [comment]
Got some bad news.

Forge 41.0.110
caelus-forge-1.19-3.0.0.3
origins-forge-1.19-1.5.0.3-fatjar

Click Singleplayer on the main screen or delete a world that's already there and crash with this error:

net.minecraftforge.fml.ModLoadingException: Origins (origins) encountered an error during the done event phase
java.lang.NoClassDefFoundError: javax/json/stream/JsonGenerationException at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:111) ~[javafmllanguage-1.19-41.0.110.jar%23147!/:?]

[crashlog](https://github.com/EdwinMindcraft/origins-architectury/files/9179928/crash-2022-07-25_19.31.44-client.txt)

**Comment by EdwinMindcraft** [comment]
Oh that's great.
Yeah, let's include a package in dev that doesn't exist in production. I'm sure that'll go well.
I'm archiving the release for now, downgrade if possible, and use commands to set your origin.

**Comment by Baggytrousers27** [comment]
Don't you just love working with forge?

**Comment by EdwinMindcraft** [comment]
It should be fixed now.

**Comment by Baggytrousers27** [comment]
Seems to be working so far (touch wood). If anything explodes or sets my dog on fire, you'll be the first to know. ¦D
Thank you for all of this by the way. Your hard work is greatly appreciated.
