### ISSUE TITLE
1.19 No texture for Orb of Origin

### ISSUE THREAD

**Issue by Inonedn** [EdwinMindcraft/origins-architectury#209]

**Comment by Illios42** [comment]
This is still an issue with v. 1.5.0.4. It literally has no textures, not even the black and pink one.

![2022-07-26_22 46 34](https://user-images.githubusercontent.com/101580687/181109135-e38e3ede-b7ac-4b75-a3a5-31ccd32c30ae.png)

**Comment by EdwinMindcraft** [comment]
1.5.0.4 was rushed out because of a critical issue. I didn't actually solve anything else in that release.
