### ISSUE TITLE
Broken nether spawning 

### ISSUE THREAD

**Issue by Yenlon** [EdwinMindcraft/origins-architectury#21]
When I chosed the blazeborn origin, this happened:
![FML early loading progress 21 05 2021 01_42_08](https://user-images.githubusercontent.com/67074171/119065548-191ad800-b9de-11eb-9e7d-e010aedbb208.png)
By the way this is 3rd person and as you can see my player character didn't even rendered and the HUD is somehow broken. I couldn't move at all, however I could open my inventory and turn my character around. I closed the world, started again and then it went fine. BUT when I died in the nether the death screen was frozen and I couldn't respawn but I could chose 'back to title screen', after that the game crashed with the following crash report. It seems that spawning in the nether after dying and especially spawning in the nether upon world creation creates lots of issues with origin!

[crash-2021-05-21_02.37.48-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/6519374/crash-2021-05-21_02.37.48-server.txt)

**Comment by EdwinMindcraft** [comment]
Should be fixed. Keeping this open in case it doesn't work.

**Comment by Yenlon** [comment]
Alright, there are no spawning issues anymore with this build :)
