### ISSUE TITLE
My 1.19 Modded Server Keeps Crashing

### ISSUE THREAD

**Issue by Thisguyneedshelp** [EdwinMindcraft/origins-architectury#210]
Everytime I try to start up it crashes shortly after, it was sort of working before i updated forge(you had to manually set origins), heres the log https://mclo.gs/JEKiqsN

**Comment by Thisguyneedshelp** [comment]
i just updated it as well to the most recent version.

**Comment by Thisguyneedshelp** [comment]
The versions you gave to some other guy with a similar problem worked so thanks!

**Comment by Aym4neDev** [comment]
can you please give me the version that he gave to some other guy?

**Comment by EdwinMindcraft** [comment]
Put the content of META-INF/jarjar in your mods folder (except for the json), and remove it from the jar.
This is a forge issue in both 1.18.2 and 1.19.
