### ISSUE TITLE
[1.18.2] I get a CTD on map start up when using the Dragon Origin from Bucolic Origins after sending them the crash log they said the issue was on your end.

### ISSUE THREAD

**Issue by Zippomoon** [EdwinMindcraft/origins-architectury#212]
[https://drive.google.com/file/d/1cbSUWvuP3WLnXv99cDGpaWxvXUDQ_ZC8/view?usp=sharing](url)

**Comment by EdwinMindcraft** [comment]
Forge just refuses to apply my mixins. I can't fix that.

**Comment by Zippomoon** [comment]
So I should report this to the Forge team then.

**Comment by EdwinMindcraft** [comment]
They probably need to update JarJar for 1.18.2.
But yeah, as far as I'm aware, unless you've changed the jar files manually those work perfectly well with 1.19.
And the build code is the exact same.

**Comment by Zippomoon** [comment]
What's the JarJar?

**Comment by EdwinMindcraft** [comment]
The system that allows Jars to be contained within other jars, that was added in 40.1.60. Right now, as far as I can tell, mixin does not recognize manifests from those files, and as such skips them. You can tell by the fact that neither of the two mods jarjar'd mods (Additional Entity Attributes and Apoli) that use mixin do not have their mixins listed anywhere even though at least one of those should be present.
I may be wrong, but I'd need either a latest.log or a debug.log to check that.

**Comment by Zippomoon** [comment]
[https://drive.google.com/file/d/14upCf35okNtJxwgYf-AY-jhAFlwfhyJ8/view?usp=sharing](url)

**Comment by EdwinMindcraft** [comment]
Don't worry, I've found the [PR that fixes the bug for 1.19](https://github.com/MinecraftForge/MinecraftForge/pull/8900). They just need to backport that one.

**Comment by Peach774** [comment]
> 

Is there anything I can do as a player to handle this in the meantime other than not playing?

**Comment by EdwinMindcraft** [comment]
In the origins jar, move all the content of META-INF/jarjar into your mods folder and remove the json file.
