### ISSUE TITLE
[1.19] Merling visual bug

### ISSUE THREAD

**Issue by Illios42** [EdwinMindcraft/origins-architectury#214]
Tested it with only origins-forge-1.19-1.5.0.4-fatjar and caelus-forge-1.19-3.0.0.3 in the mods folder. When picking Merling and entering water their vision blinks between something almost like blindness and normal, not-merling underwater vision. The player essentially turns black for a few seconds before changing back to normal, see below:

![2022-07-26_22 53 47](https://user-images.githubusercontent.com/101580687/181109979-50955ac0-6c26-44f0-8ab9-a53b09adce34.png)

When you first enter the water

![2022-07-26_22 46 06](https://user-images.githubusercontent.com/101580687/181109728-af3a400c-45c3-4e33-8401-a2ee22a04ca8.png)

A couple seconds later, rinse and repeat.

**Comment by WelderFish81** [comment]
I also have the same issue with the Merling Origin, plus Auqa Affinity does not work correctly.

**Comment by DarkSoulMastery** [comment]
The 1.19 is still in beta and doesn't fully function for all origins yet, Edwin is still fixing the bug right now
