### ISSUE TITLE
Origins:Classes incompatibility due to item duplication

### ISSUE THREAD

**Issue by cassowarycasper** [EdwinMindcraft/origins-architectury#216]
Minecraft Version: 1.18.2
Please see: https://github.com/LimonBlaze/origins-classes-forge/issues/11 and https://github.com/LimonBlaze/origins-classes-forge/issues/15

Essentially, origins:starting_equipment is making it so that every time someone logs onto the server or dies and respawns, they get duplicate starting items.

**Comment by DaddyP1G** [comment]
I'm also having this problem.   Nothing shows in logs.  Tried to set  "recurrent": false also doesn't work.

**Comment by ChrysanthCow** [comment]
Duplicate of #345
