### ISSUE TITLE
attribute modifiers not working for some reason [1.18.2]

### ISSUE THREAD

**Issue by ggezgaming** [EdwinMindcraft/origins-architectury#219]
i think i';ve done everything correctly as i do know a bit about making origins, but in my code for some reason i keep getting this error, saying that the attribute and conditioned attribute is an unknown registry key (whatever that means)

error:

Power "squishy:toggleaction1" will only be partially loaded: Unknown registry key: origins:attribute, At ResourceLocation: JsonObject; Unknown registry key: origins:attribute, At ResourceLocation: JsonObject, At ResourceLocation: JsonObject

i tried both attribute and conditioned_attribute, looked over the spelling of the file and everything seems to be working fine

Code is attached, it might be a rookie mistake, or potentially just a little bit of a change regarding the forge vs fabric version
`{
    "type": "origins:action_over_time",
    "interval": 1,
    "entity_action": {
        "type": "origins:and",
        "condition": {
            "type": "origins:resource",
            "resource": "*:toggleresource",
            "comparison": "==",
            "compare_to": 1
        },
        "actions": [{
        "type": "origins:execute_command",
        "command": "/title @s actionbar {\"texr\":\"Berserker mode activated\",\"color\":\"dark_red\"}"
    },
    {
        "type": "origins:attribute",
        "modifier": {
            "attribute": "minecraft.generic.max_health",
            "operation": "addition",
            "value": -10
        },
        "tickrate": 1
    },
    {
        "type": "origins:attribute",
        "modifier": {
            "attribute": "minecraft.generic.attack_damage",
            "operation": "addition",
            "value": 5
        }
    }
    ]
  }
}`

**Comment by EdwinMindcraft** [comment]
You cannot apply attributes as an action, use the power [`origins:conditioned_attribute`](https://origins.readthedocs.io/en/latest/types/power_types/conditioned_attribute/) instead.
