### ISSUE TITLE
[SUGGESTION] Movable Active bar

### ISSUE THREAD

**Issue by zEpiixz** [EdwinMindcraft/origins-architectury#22]
Mods like ElenaiDodge 2 is having a bar exactly where the bar for the Ability is and so it clashes. 
But because the Dodge bar is Always active and the ability bar is most of the time only visible when using it, then it would be nice to have a way to move it.

**Comment by EdwinMindcraft** [comment]
You can change the position of the bar by modifying xOffset and yOffset in origins.toml.
Setting yOffset to a negative value will raise the bar.
