### ISSUE TITLE
Server Crashes on Startup

### ISSUE THREAD

**Issue by AhhhhJustKidding** [EdwinMindcraft/origins-architectury#221]
[New Paste 1.txt](https://github.com/EdwinMindcraft/origins-architectury/files/9229918/New.Paste.1.txt)

**Comment by altron34** [comment]
I've been having the same problem as well. I hope they can fix it quickly cause I really want to play on a server with friends and i can't with fabric because i have mac problems same as my other friends

**Comment by EdwinMindcraft** [comment]
This is a forge issue, Orion is working on fixing it, please just wait.
