### ISSUE TITLE
[1.16.5] Conflicts with Astral Sorcery mod, can't place down Liquid Starlight

### ISSUE THREAD

**Issue by PsycomaticPenguin** [EdwinMindcraft/origins-architectury#227]
After playing around with Valhelsia 3 with some additional mods added in, I noticed that I couldn't place down liquid starlight from my buckets, preventing me from progressing through the rest of the content within Astral Sorcery. After some digging around, I found a similar issue about this, and narrowed the issue down to Origins after some trial and error. Is there anything that can be done about this?

**Comment by EdwinMindcraft** [comment]
I basically consider 1.16 to be end of life. I'm willing to publish updates, but if you want something done, make a pull request.

**Comment by PsycomaticPenguin** [comment]
Okay, thank you for your response.
