### ISSUE TITLE
1.18.2 dont work

### ISSUE THREAD

**Issue by albertosaurio65** [EdwinMindcraft/origins-architectury#229]
![image](https://user-images.githubusercontent.com/70109413/184157091-f1f06117-6060-4670-905f-fe9e4cb84f95.png)
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/9309471/latest.log)

[11ago2022 16:27:22.314] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing mandatory dependencies: apoli, forge, calio

dependencies are supposed to come inside the mod

**Comment by EdwinMindcraft** [comment]
Downgrade.
