### ISSUE TITLE
[1.19/1.18] Origins Forge crashes on servers

### ISSUE THREAD

**Issue by Aym4neDev** [EdwinMindcraft/origins-architectury#232]
Hello, recently i and my friends were trying to make an origins server that uses Quark and this mod. When ever we try to start the server it crashes with the report : 
Failed to load mod file META-INF/jarjar/Forge-1.0.1-1.19.jar from origins-forge-1.19-1.5.0.4-fatjar.jar

I'm not sure what's wrong but if possible you can tell me if this issue is going to be fixed in an upcoming version or if there is a way to fix it.

**Comment by BlazeTheProtogen** [comment]
I have been having this EXACT SAME bug with my server, thanks for telling me what was causing it!

**Comment by EdwinMindcraft** [comment]
This is a forge bug for 1.19 & 1.18. Extract the included mods (META-INF/jarjar/*.jar) into the mods folder for now.
The issue can be solved by using forge 42.0.2, but I know the code breaks slightly between 1.19 and 1.19.2, so it may not be binary compatible, and your users probably won't want to modify their mods just to play on 1.19.1+.

For players still using 1.5.0.2 for 1.18.2, downgrade back to 1.5.0.1 for now.

**Comment by EdwinMindcraft** [comment]
The other solution is to download the non-fatjar files from the github releases and replace origins with those (all 4 are required).
