### ISSUE TITLE
forge server running the mod won't work.

### ISSUE THREAD

**Issue by NmsIsCool** [EdwinMindcraft/origins-architectury#238]
I am running a forge server through pebble host. Small little thing. Not too big. Anyways, Forge with no mods ran fine. Forge with the caelus dependency mod ran fine but origins threw a fit.
gave me something like this: https://mcpaste.io/c61cf5163f4a5549
I am using forge 41.1.0 game version 1.19
the origins mod version is 1.5.0.4 on game version 1.19
the caelus mod version is 3.0.0.3 game version 1.19
I tried opening up the origins jar file (It was a fatjar. All that was on curse forge) and found apoli-forge-1.19-2.3.4.2.jar, caelus-forge-1.19-3.0.0.3.jar, and Forge-1.0.1-1.19.jar in  **META_INF/jarjar/**
When I added all 3 of those to the server mods folder and added them to my client, then removed the origins mod jar file, the server started up fine. Only thing was, no origins. Just plain minecraft with those 3 things and forge.
Any idea whats up?

**Comment by EdwinMindcraft** [comment]
Update to 1.19.2. JiJ is busted before then.
