### ISSUE TITLE
[Bug - 1.19] Method modify_healing does not exist.

### ISSUE THREAD

**Issue by fireheart3911** [EdwinMindcraft/origins-architectury#240]
Failed to load power originplus:noheal because Method modify_healing could not be found

=> All powers with modify_healing do not work

**Comment by EdwinMindcraft** [comment]
Modify healing is a Origins 1.6 feature, which isn't supported yet.

**Comment by ChrysanthCow** [comment]
Modify Healing is now supported as of Origins Forge 1.7.1.0
