### ISSUE TITLE
Operations others than addition do not work

### ISSUE THREAD

**Issue by spicysnake** [EdwinMindcraft/origins-architectury#243]
For the modifier field for powers that use it, most if not all of the modifier do not work. Addition does work but when you use another modifier the power no longer appears in game.

**Comment by EdwinMindcraft** [comment]
Please state your version, and more importantly, check your logs.
If you're running 1.18+, Apoli should state exactly what is wrong and where. Search your power name in the logs to try and find it.
Valid types should be `"addition"`, `"multiply_base"` and `"multiply_total"`.

**Comment by spicysnake** [comment]
Sorry about that, I am on 1.19 and I checked the logs and saw that everything worked with the three types you mentioned. I found out that the issue is that the mod does not currently support the new valid types of operations that the fabric version [uses](https://origins.readthedocs.io/en/latest/types/data_types/attribute_modifier_operation/) as the logs say that there is no value listed in code even though there is.

**Comment by ChrysanthCow** [comment]
The mod now supports the other types that were mentioned here as of 1.7.1.0.
