### ISSUE TITLE
Cant join server 1.19.2 forge 41.3.30

### ISSUE THREAD

**Issue by Thisguyneedshelp** [EdwinMindcraft/origins-architectury#258]
I keep getting this error in the console 
l='ServerLevel[forge_1_19_2_1952206]', x=-205.50, y=79.00, z=407.50] logged in and will be protected for 90 secs.
29.09 15:06:41 [Disconnect] User DecapodDan has disconnected, reason: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.toString()" because "p_130086_" is null

**Comment by Zeekicus** [comment]
Same issue for me did you happen to find any fix?
