### ISSUE TITLE
If you have no origin, you Just stop taking damage

### ISSUE THREAD

**Issue by LeonariX58** [EdwinMindcraft/origins-architectury#267]
Version: 1.18.2 Forge (Can't remember the file version)

You can Skip the origin selecta Gui by making a Kubejs Client Script to close it, so when you have no origins somehow you Just take no damage.

I'm not on PC right now, but when I get home I can  show How I did It.

**Comment by EdwinMindcraft** [comment]
KubeJS allowing clients to close UIs is already an oversight because it can break a lot of things.
