### ISSUE TITLE
[1.19.2] Invalid Player Data, Apoli Related

### ISSUE THREAD

**Issue by whiteglovian** [EdwinMindcraft/origins-architectury#275]
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/10097800/latest.log)
My game is heavily modded, I'm not sure if it's an incompatibility-related error. My mods are listed in the log.
I've tried editing the .Jar, which fixed the error, but I completely forgot what I did, and accidentally overwritten it, so I'm back at square one.
It doesn't crash Minecraft, just the world itself. It happens every time I try to load any world, regardless of what I do.
UPDATE: I fixed it! It wasn't Origins at all! it was Origins++. I forgot it needs XL Packets and doesn't install automatically with the mod

**Comment by ChrysanthCow** [comment]
Closed as op has mentioned that they solved it.
