### ISSUE TITLE
Crashes after selecting Blazeborn, Enderian, Merling or Phatom. Minecraft 1.18.2 Forge 40.1.86

### ISSUE THREAD

**Issue by VoidOloth** [EdwinMindcraft/origins-architectury#280]
So, small group of us are trying out Origins on a server and it started booting us off. To troubleshoot had one of the players try a offline world and it caused the game to crash. Tried some trouble shooting with rolling back Forge and such and same issue, might not be rolling back father enough. Thank you in advance for your time, and for the time maintaining this mod.
[Log.txt](https://github.com/EdwinMindcraft/origins-architectury/files/10215244/Log.txt)

Update..
We tried unloading all mods but Origins, and it still was having the issue. Still using 1.18.2 and Forge 40.1.82 with the Origins 1.5.0.1 I think. My first guess would be we're missing a library maybe? as the Spider origin can't climb walls and the Feline sometimes loses the ability to scare off creepers( Which I read is more an issue with minecraft and not the mod though)

of note the Server its self dose not crash and only seems to boot the client.

**Comment by nullive** [comment]
the same thing is happening to me at first i thought it was my graphics driver being weird but i restarted everything and its still booting me out of the server

**Comment by FernoXL** [comment]
Having the Same Issue.

**Comment by BasquiatThe1** [comment]
Having the same/similar issue. When I create a singeplayer game and go in for the first time and choose Enderian, the screen turns black and then it says "Connection Lost - Server Closed" and gives me a Return to Server List button. Which takes me back to the multiplayer server list. Which is extrremely odd since it's a singleplayer world. Don't know if the issue consists with other Origins.

Using 1.182 - Forge 40.1.84

**Comment by Aragorn195** [comment]
Same issues as this. I have added the crash reports for Blazeborn, Enderian, Merling, and Phantom from my testing in Singleplayer.
[Enderian Crash.txt](https://github.com/EdwinMindcraft/origins-architectury/files/10329044/Enderian.Crash.txt)
[Blazeborn Crash.txt](https://github.com/EdwinMindcraft/origins-architectury/files/10329045/Blazeborn.Crash.txt)
[Merling Crash.txt](https://github.com/EdwinMindcraft/origins-architectury/files/10329046/Merling.Crash.txt)
[Phantom Crash.txt](https://github.com/EdwinMindcraft/origins-architectury/files/10329047/Phantom.Crash.txt)

**Comment by stearman10** [comment]
I added this mod and dependent libraries to Better MC [FORGE] - BMC2, in 1.18.2 running forge version 40.1.69, and can confirm selecting these classes does immediately hard crash my entire game client.

**Comment by ShiftyFly** [comment]
same here, on forge 40.2.0 with mod version 1.5.0.1
selecting merling gives this crash report:
Error: java.lang.ClassCastException: class net.minecraft.client.player.LocalPlayer cannot be cast to class io.github.apace100.apoli.mixin.EntityAccessor (net.minecraft.client.player.LocalPlayer is in module minecraft@1.18.2 of loader 'TRANSFORMER' @2b1cd7bc; io.github.apace100.apoli.mixin.EntityAccessor is in module apoli@1.18.2-2.3.4.0 of loader 'TRANSFORMER' @2b1cd7bc)
selecting phantom gives this crash report: 
java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class io.github.apace100.apoli.mixin.EntityAccessor (net.minecraft.server.level.ServerPlayer is in module minecraft@1.18.2 of loader 'TRANSFORMER' @64deb58f; io.github.apace100.apoli.mixin.EntityAccessor is in module apoli@1.18.2-2.3.4.0 of loader 'TRANSFORMER' @64deb58f)
i should assume that the others are similar, though i didn't test blazeborn
to make it worse, it seems that the world crashes even when you load in if you are one of these origins
