### ISSUE TITLE
After Death Losing Size

### ISSUE THREAD

**Issue by FestiveSloth** [EdwinMindcraft/origins-architectury#281]
Hello! I recently Created a Mohist Server with the Files for Medieval Minecraft 1.16.5 ( Forge ), Upon Joining I chose Dwarf, Once I die I immediately lose my Small size. Hoping there's a fix for this?

**Comment by Seagoddess** [comment]
Are you using the Pehkui mod? If so there is a toggle-able command that keeps the size after death. 
/scale persist set <true|false> [entity]

To my knowledge dwarf doesn't normally downscale anyways, but if it does it's probably using this mod as a way of adjusting the size.

**Comment by FestiveSloth** [comment]
> Are you using the Pehkui mod? If so there is a toggle-able command that keeps the size after death. /scale persist set <true|false> [entity]
> 
> To my knowledge dwarf doesn't normally downscale anyways, but if it does it's probably using this mod as a way of adjusting the size.

This Mod is part of the Modpack I'm playing on. This helped me a lot! I was having to leave the server and rejoin anytime I died.
