### ISSUE TITLE
Resource Value doesnt work

### ISSUE THREAD

**Issue by HoodBlah** [EdwinMindcraft/origins-architectury#287]
forge 1.19.2

Using the value of a resource bar as the value for an attribute change doesnt work. 

In this origin, the scaling power has the re power as the value for health and armor. but increasing the resource does nat give health or armor.

[GoldenDragon.zip](https://github.com/EdwinMindcraft/origins-architectury/files/10461976/GoldenDragon.zip)

**Comment by EdwinMindcraft** [comment]
Modify attribute isn't implemented in forge yet.
