### ISSUE TITLE
Incompatible with Corail Tombstone

### ISSUE THREAD

**Issue by jennykitten78** [EdwinMindcraft/origins-architectury#289]
### Minecraft Version
1.19.2

### Forge Version
43.2.0

### Origins Version
1.5.0.6

### What Happened?

I was trying to add Origins to All the Mods 8 when it would crash. It seems to be related to Corail Tombstone included with the mod pack. I have posted an issue on Corail Tombstone issues tracker as well.

[latest.log](https://gist.github.com/jennykitten78/a4d2c25d1dcf52976e35042d08dded90)

[crash-2023-02-01_12.10.02-client.txt](https://gist.github.com/jennykitten78/db4036e0439ffc4af1d46f29f1259fd9)

Thank you for taking the time to view this issue report!

**Comment by Corail31** [comment]
https://github.com/Corail31/tombstone_lite/issues/134
