### ISSUE TITLE
Server Crash upon enderian teleport.

### ISSUE THREAD

**Issue by MikeLauwers** [EdwinMindcraft/origins-architectury#29]
Hi

 a couple of friends and I have started a small modded server with a couple of mods. 
We didn't used to have a problem in the start with the Enderian but now every time she teleports it crashes the server. 
I've added the error message/crash message to this issue. 
I've also added the mod-pack and config files of these from a custom profile on curse-forge. You can import it on curse-forge to install it if you want to check out what's going on. 

Thanks in advance! 

[message.txt](https://github.com/EdwinMindcraft/origins-architectury/files/6642014/message.txt)

[MODDED WITH FRIENDS.zip](https://github.com/EdwinMindcraft/origins-architectury/files/6642020/MODDED.WITH.FRIENDS.zip)

**Comment by EdwinMindcraft** [comment]
Use the latest release of forge instead of the recommended.
