### ISSUE TITLE
Severe issues with origin datapack

### ISSUE THREAD

**Issue by Lightveld** [EdwinMindcraft/origins-architectury#295]
When picking the Futara origin in the attached datapack, using the secondary origin keybind doesn't always swap between abilities correctly and switching abilities on and off doesn't work properly

Flame burst cannot be swapped back to after swapping off it
Healing power can't be turned back off after turning on, same as energy orbs

[FutaraDragon_Origin_v21_MC_1_19.zip](https://github.com/EdwinMindcraft/origins-architectury/files/10853440/FutaraDragon_Origin_v21_MC_1_19.zip)

**Comment by EdwinMindcraft** [comment]
The zip file you've attached is empty. If this is a recent datapack, the issue is that some parts of the implementation are missing.

**Comment by Lightveld** [comment]
Whoops, looks like I attached it wrong as it was inside another zip.

The datapack is a year or two old now and doesn't work in 1.17, 1.18, or 1.19
[FutaraDragon_Origin_v21_MC_1_19.zip](https://github.com/EdwinMindcraft/origins-architectury/files/11057123/FutaraDragon_Origin_v21_MC_1_19.zip)
