### ISSUE TITLE
removal of all origins and powers

### ISSUE THREAD

**Issue by Ice424** [EdwinMindcraft/origins-architectury#296]
using a custom made origins data pack and am setting it up on my server and this keeps happening when you log into the world there is no origin selection screen, no orb of origin and using commands doesn't work

Have got this issue on both 1.19 and 1.19.2

`Server thread/WARN16:20:08
Power "chill:ferrari/hands" will only be partially loaded: Failed to read fields: Error reading Operation: No value was found for name: "set_total"
Server thread/ERROR16:20:08
Error loading power "chill:short/fall": Unknown registry key: origins:from_falling, At ResourceLocation: JsonObject; Error reading Operation: No value was found for name: "add_base_late"
Loading for all instances of power chill:short/fall failed.
Error loading power "chill:bee/speed_jump": Unknown registry key: origins:modify_velocity
Loading for all instances of power chill:bee/speed_jump failed.
16:20:09
Error loading power "chill:frog/fall": Unknown registry key: origins:from_falling, At ResourceLocation: JsonObject
Loading for all instances of power chill:frog/fall failed.
Error loading power "chill:short/speed_jump": Unknown registry key: origins:modify_velocity
Loading for all instances of power chill:short/speed_jump failed.
Error loading power "chill:saga/refuel": Unknown registry key: origins:modify_inventory, At ResourceLocation: JsonObject
Loading for all instances of power chill:saga/refuel failed.
Error loading power "chill:tumtum/crafting": Unknown registry key: origins:drop_inventory, At ResourceLocation: JsonObject
Loading for all instances of power chill:tumtum/crafting failed.
Removed 4 missing powers from chill:bigm
Removed 5 missing powers from origins:enderian
Removed 6 missing powers from chill:short_one
Removed 20 missing powers from chill:bee
Removed 6 missing powers from origins:feline
Removed 5 missing powers from origins:elytrian
Removed 3 missing powers from chill:frog
Removed 7 missing powers from origins:phantom
Removed 7 missing powers from origins:blazeborn
Removed 4 missing powers from chill:tallboi
Removed 5 missing powers from origins:avian
Removed 4 missing powers from chill:saga
Removed 4 missing powers from chill:death
Removed 1 missing powers from chill:possessed
Removed 15 missing powers from chill:nightrunner
Removed 2 missing powers from chill:support
Removed 7 missing powers from chill:icy
Removed 5 missing powers from origins:shulk
Removed 4 missing powers from chill:theo
Removed 11 missing powers from chill:tumtum
Removed 7 missing powers from origins:merling
Removed 4 missing powers from origins:arachnid
Removed 9 missing powers from chill:banan
Removed 6 missing powers from chill:ferrari`

**Comment by EdwinMindcraft** [comment]
A power failed to load because it uses a feature that isn't currently implemented in forge.

**Comment by Ice424** [comment]
I assumed was just wondering if there was anything more. Is there a list of supported and unsupported powers/actions/conditions

**Comment by EdwinMindcraft** [comment]
Not really. The way to know is basically taking the version of the mod you're using (here apoli), and considering the first 3 numbers. Those numbers are the fabric version on which the current mod is built. For apoli that's 2.3.4.
If you want to have a list and are willing to read some code, the classes can be found at in [this folder](https://github.com/EdwinMindcraft/apoli/tree/1.19.x/1.6/src/main/java/io/github/edwinmindcraft/apoli/common/registry).

**Comment by Ice424** [comment]
Thanks

**Comment by satoon10** [comment]
> A power failed to load because it uses a feature that isn't currently implemented in forge.

Does that mean that the port is incomplete? I'm confused
