### ISSUE TITLE
Creeper Origin (Forge)

### ISSUE THREAD

**Issue by JaxJix** [EdwinMindcraft/origins-architectury#298]
The Creeper Origin in my multiplayer keeps randomly exploding even if my hand are not on my keyboard.

Please have a look at it but take your time!

Thank you for taking the time of day/night to read this and have a good day/night.

**Comment by EdwinMindcraft** [comment]
Creeper origin is provided by another mod or datapack. This is not something built into the mod, please ask the person that created the origin for help.
