### ISSUE TITLE
Datapack crashes world

### ISSUE THREAD

**Issue by WhySoBleu** [EdwinMindcraft/origins-architectury#3]
I wanted to test if the datapack rebalanced origins for origins might work, but whenever I load the world up, it just closes the game. (I thought it was my datapack but was just this one for some reason) Anyways, here's the log:

[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/6399644/latest.log)

**Comment by WhySoBleu** [comment]
[Rebalanced_Origins_v3.0.zip](https://github.com/EdwinMindcraft/origins-architectury/files/6400179/Rebalanced_Origins_v3.0.zip)
here's the datapack aswell

**Comment by EdwinMindcraft** [comment]
Latest version should fix this issue.
