### ISSUE TITLE
Other Origins respawning in nether 

### ISSUE THREAD

**Issue by einasota** [EdwinMindcraft/origins-architectury#30]
On my server, other origins besides Blazeborn die and are respawning in nether, even without having entered nether or created the portal. It's happening in the Forge Version

**Comment by EdwinMindcraft** [comment]
Not on my end, check your mod list for another mod that might do that.

**Comment by heatcrash** [comment]
> 
> 
> On my server, other origins besides Blazeborn die and are respawning in nether, even without having entered nether or created the portal. It's happening in the Forge Version

I'm having the same issue, did you figure out what was causing it on your end?

**Comment by mosharky** [comment]
Having this problem right now too, any solutions?
