### ISSUE TITLE
game crashes when i try to open the game with mod installed error code 1

### ISSUE THREAD

**Issue by liamwerk7676** [EdwinMindcraft/origins-architectury#306]
i aqm using origens forge and i dont know why it crashes can anyone help ?

**Comment by EdwinMindcraft** [comment]
This gives me no information at all. Please state at the very least the version of the mod you're using and if you can the crash report. (<Minecraft Install Dir>/crash-reports/)

**Comment by xd4rkzghost01** [comment]
I can't give anymore info, but the last update (03-28) keep crashing the game with Exit Code-1. And we can't give any log since the game won't launch. Go Back to 1.19.2 1.5.0.6 solve the issue.

**Comment by EdwinMindcraft** [comment]
Addons may not have updated yet.
1.7 is has a breaking change.

**Comment by liamwerk7676** [comment]
im so so sorry for wasting youre time and aslo i dont know what i was thinking when making this bug report im just going to close this becus i think it was essentials and quilt wich are both fixed in my modpack so again im so so sorry for wasting anyone`s time
