### ISSUE TITLE
Is there a way to make shields from other mods unable to be equipped by origins like the shulk?

### ISSUE THREAD

**Issue by HereToSaySomething** [EdwinMindcraft/origins-architectury#308]
I saw that in the fabric version, there was a tag called origins:shields that you could add to shields from other mods to make them work with the shulk origin. Is there something similar in the Forge version? 

Here is the link to the resolved origin-fabric issue: https://github.com/apace100/origins-fabric/issues/56

**Comment by EdwinMindcraft** [comment]
Doesn't the fabric fix work?
If not that's a bug.

**Comment by HereToSaySomething** [comment]
Well where do I put the tag?

**Comment by EdwinMindcraft** [comment]
In a datapack at `data/origins/tags/items/shields.json`
You can see the original [here](https://github.com/apace100/origins-fabric/blob/1.19/src/main/resources/data/origins/tags/items/shields.json)

**Comment by HereToSaySomething** [comment]
Forgive me for asking, but where do I access that data pack?

**Comment by HereToSaySomething** [comment]
In the config?

**Comment by EdwinMindcraft** [comment]
You have to make a datapack, you should find a guide on the minecraft wiki.
Once that is done, you either put in the datapacks folder of your save, or, for a new world, you can drag it into the datapacks screen while creating the world.
That's a bit weird, and I know some mods allow you to have always active datapacks, without having to load them every time you create a new game, but I can't remember which ones.
If you're using KubeJS, you can add the items you want that way [Tags (KubeJS Wiki)](https://mods.latvian.dev/books/kubejs/page/tags)

**Comment by HereToSaySomething** [comment]
Does that work for a modded server as well?

**Comment by EdwinMindcraft** [comment]
Every option should work on both the client and the server.
To be more precise, only the server is required to have the changes (datapack or KubeJS), since that information will then be sent to every client connecting to it.

**Comment by HereToSaySomething** [comment]
I am confused about how this works. In the data pack that I create, do I need to add a new folder to the data folder called "origins," then in that folder create another folder named "tags," and then in that folder create another folder named "items," and in that folder create a file called "shields.json," and then in that file copy and paste the following code? : `{
  "replace": false,
  "values": [
    "minecraft:shield"
  ]
}`

**Comment by HereToSaySomething** [comment]
and then do I add the other shields in quotations like the "minecraft:shield" for example "blue_skies:spike_shield"?

**Comment by HereToSaySomething** [comment]
like this?
![image](https://user-images.githubusercontent.com/79809777/227813832-92dac79d-196d-4be6-add9-686d18b87c3a.png)

**Comment by EdwinMindcraft** [comment]
Yes, you just need to use a comma to separate the strings, so
```
"minecraft:shield",
"blue_skies:spike_shield"
```
Also you shouldn't need to specify the vanilla shield as it's already handled by the original mod, but keeping it won't hurt.

**Comment by HereToSaySomething** [comment]
I did it! Thank you so much for your help, and for helping at such short notice!

**Comment by HereToSaySomething** [comment]
I have another question. How do I send my data pack to other people?
Or even be able to apply the data pack when I create a new world? 

I was able to get it to work in one world, but I'm having trouble making it work in a different world.

**Comment by HereToSaySomething** [comment]
@EdwinMindcraft

**Comment by HereToSaySomething** [comment]
never mind I figured it out.
