### ISSUE TITLE
crash when booting. exit code 1 [1.19.2]

### ISSUE THREAD

**Issue by Xplodin** [EdwinMindcraft/origins-architectury#313]
mixin fails due to (I think) origins forge and obscuria

[debug.log](https://github.com/EdwinMindcraft/origins-architectury/files/11108777/debug.log)

**Comment by MrBOOMberMAN** [comment]
i can confirm: is a incompatibility with obscuria mods

**Comment by AngelOfCreation** [comment]
Why did I receive an email for this? I'm not even a part of this thread.

**Comment by Darkmega18** [comment]
well frick. is there anything that can be done? :< I have this issue also.

**Comment by ChrysanthCow** [comment]
This issue is on our end. I've made a change to the mixin that is causing the incompatibility to be safer when it comes to collisions.

**Comment by ChrysanthCow** [comment]
This should be fixed on their end as of Obscure API 15, but this doesn't mean that we won't fix our code that's at fault to prevent situations like this from happening in the future.

**Comment by Darkmega18** [comment]
noice.
