### ISSUE TITLE
crash when loading world / changing origin

### ISSUE THREAD

**Issue by oopsiespooks** [EdwinMindcraft/origins-architectury#314]
i'm currently working on my own origins datapack, and out of nowhere (quite literally), minecraft is consistently crashing. i have had no problems in 1.16.5 or 1.18.2 until yesterday and cannot understand how to fix or understand what the problem is. 

i hope im submitting this issue in the right place as ive never done this before

am happy to give more information on the crash if needed :) 

---- Minecraft Crash Report ----
// Why did you do that?

Time: 3/31/23, 2:38 PM
Description: Ticking player

java.lang.ClassCastException: class net.minecraft.server.level.ServerPlayer cannot be cast to class io.github.apace100.apoli.mixin.EntityAccessor (net.minecraft.server.level.ServerPlayer is in module minecraft@1.18.2 of loader 'TRANSFORMER' @30839e44; io.github.apace100.apoli.mixin.EntityAccessor is in module apoli@1.18.2-2.3.4.0 of loader 'TRANSFORMER' @30839e44)

**Comment by EdwinMindcraft** [comment]
That's just a mixin not being applied. Don't use 1.5.* Forge's JiJ doesn't work properly.

**Comment by EdwinMindcraft** [comment]
(I mean you can, but you need to use separate jar files, and which you'll find in the releases)

**Comment by oopsiespooks** [comment]
this worked !! thank you so much for the quick reply :D
