### ISSUE TITLE
[SOLVED] origins:starting_equipment does not check recurrent field values at all.

### ISSUE THREAD

**Issue by bypassblitz** [EdwinMindcraft/origins-architectury#315]
origins:starting_equipment

and the

"recurrent": false

field does not operate at all.

![image](https://user-images.githubusercontent.com/129369435/229255998-fffb4645-5c7d-4113-95df-493f93a6fc80.png)
[humanadventure.log](https://github.com/EdwinMindcraft/origins-architectury/files/11128014/humanadventure.log)

**Comment by bypassblitz** [comment]
Due to recurrent not being checked, each time the player dies origins:starting_equipment gives the player another copy of their starting inventory.

**Comment by bypassblitz** [comment]
apoli:starting_equipment

Works as an alternative.
1.18.2

**Comment by Diskman20** [comment]
I am having the same issue on 1.19.2, is there a way to fix it?

**Comment by bypassblitz** [comment]
> I am having the same issue on 1.19.2, is there a way to fix it?

The best solution is to just not use this broken pos, origins&apoli don't work, my best solution is to run a command giving items when players get stone age advancement. Unlike origins&apoli:starting_equip players can only get stone age one time.

https://cdn.discordapp.com/attachments/825449766384828476/1094386605353095301/genesis.json

You can otherwise find it in the power library in origins discord, called "starting equipment power template".
