### ISSUE TITLE
[1.18.2]After playing for a while, the origins GUI goes wrong

### ISSUE THREAD

**Issue by ColaLiao** [EdwinMindcraft/origins-architectury#316]
![image](https://user-images.githubusercontent.com/16384174/229266772-4c0ceb9c-161d-4fc3-99d7-28daf99c1b70.png)

After playing for a while, the origins GUI become like this,

I still have origins powers, but i can't view the GUI detail.

**Comment by bypassblitz** [comment]
I discovered a rare bug? where if you close minecraft and open it again, and load the world again; you will not have any origin powers at all, not just the info-screen, but the whole power-set is missing.

But it does not happen when just closing to main menu and re-opening.

And of course, when I tried to record it happening the game behaved, and did not wig out.

(I would wonder if going to a new dimension ingame, and going back might fix that, if it ever happens again)?

**Comment by bypassblitz** [comment]
Just happened again, changing dimensions does not restore origin powers, and origin powers from mods and datapacks cease to exist on the player. Kind of ruins the whole experience.

**Comment by Darkfossill** [comment]
having the same issue in 1.19.2 in both release, sometimes the descriptions reappear but the powers don't
origins-forge-1.19.2-1.7.1.0-all.jar
origins-forge-1.19.2-1.5.0.6-all.jar

**Comment by ChrysanthCow** [comment]
> Just happened again, changing dimensions does not restore origin powers, and origin powers from mods and datapacks cease to exist on the player. Kind of ruins the whole experience.

This has been replicated in my developer environment. I'll look into fixing this asap,

**Comment by ChrysanthCow** [comment]
This was an issue of us forgetting to sync a player's origin when they swap dimensions, powers were synced but not origins. Which caused this issue in the first place.
