### ISSUE TITLE
[1.19.2] block_collision condition ignores provided block_condition

### ISSUE THREAD

**Issue by notWaterGuy12** [EdwinMindcraft/origins-architectury#319]
I was experimenting with an idea for a mechanic in a modpack, and when I used the action_over_time power with a block_collision condition, it ignored the block condition I gave it. Tested using "block" and "in_tag" conditions, both of which didn't work.

**Comment by eggohito** [comment]
The `block_condition` field was added to the `block_collision` entity condition type in Origins 1.8.0 (official Fabric version). The unofficial Forge port currently only has 1.7.x ported

**Comment by ChrysanthCow** [comment]
Not planned for 1.19.2, as mentioned by eggohito above, but you'll be able to access this field when Origins Forge updates,
