### ISSUE TITLE
Merling Can Breathe on land, seemingly, due to better diving.

### ISSUE THREAD

**Issue by Darkmega18** [EdwinMindcraft/origins-architectury#32]
I have a number of mods, but the basics are:

Origins forge: Origins-1.16.5-0.7.3.5-forge.jar
Using forge version: 36.1.24

I'm using it with a probably quite obvious compatibility issue maker with these kind of gameplay changes: **Better diving**.

It seems my breathe meter is not affected above water nor does it instead use the better diving breathe meter (45 secs at base). Although the breathe meter correctly appears when in water but doesn't tick down due to the ability to breathe in it and is hidden above ground cause it's not being reduced... oooor it's being replenished faster than I can suffocate cause better diving believes I should be capable of breathing and isn't taking the merling into account and so refills itself?

I have a relatively large compliment of other mods, but I'd suspect this is just cross compat issues between these two.

**Comment by EdwinMindcraft** [comment]
So.. I took a look at the code from better diving. I'm not able to find anything that would cause interactions to fail.
We are both modifying different methods. I know it may sound dumb, but are you on the latest version of BetterDiving? It had a heavy cleanup done to the ASM part. The prior version might have caused some issues.

**Comment by Darkmega18** [comment]
it is the latest version. I have a feeling it's cause better diving thinks my breathe meter is full and I'm on land so I should be able to breathe, and so it refills itself, faster than the merling cause suffocate on a lack of water in the air using whatever methods you use to invert the breathing.

**Comment by EdwinMindcraft** [comment]
Found the bug. I should be able to fix it.

**Comment by Darkmega18** [comment]
naisu.
