### ISSUE TITLE
[1.16.5] Datapack working on Fabric but not on Forge

### ISSUE THREAD

**Issue by Exokyhh** [EdwinMindcraft/origins-architectury#320]
I've created a datapack with the purpose of giving the player a different item based on the origin he chose, via Advancements. My modpack is in 1.16.5 forge version 36.2.34, and uses this version: 
**_Origins-1.16.5-0.7.3.9-forge.jar_**

After the player chose his origin, the datapack doesnt give him any item, even tho the file format is correct. I tried running in with fabric and Origins-1.19.2-1.7.1.jar, and there it works. 
Datapacks are supposed to work on both versions, so what's the problem? Am I missing something?

Here is the datapack (not complete, but enough to test its purpose).
[Drafts.zip](https://github.com/EdwinMindcraft/origins-architectury/files/11211500/Drafts.zip)

Note: the item the datapacks gives you comes from this mod ([EverPotion](https://www.curseforge.com/minecraft/mc-mods/everpotion)), so if the mod is not installed it's normal that you don't get any item after successfully choosing your origin.

**Comment by ChrysanthCow** [comment]
~~If you were using 1.19.2 powers on 1.16.5, where they don't exist yet, that's probably your issue here.~~

I misread your issue.

**Comment by ChrysanthCow** [comment]
I think that the `origins:chose_origin` advancement trigger does not exist on 1.16.5. You may be better off using an Action on Callback power, to achieve the same effect.

https://origins.readthedocs.io/en/0.7.3/

Here's the docs for 1.16.5 specifically.
