### ISSUE TITLE
Weird event calls for entity_action

### ISSUE THREAD

**Issue by SiverDX** [EdwinMindcraft/origins-architectury#332]
Type: `origins:action_on_callback`

When leaving a world:
`entity_action_removed`

When joining a world:
n/a

When chosing a power:
`entity_action_removed`
`entity_action_lost`

When a power is chosen:
`entity_action_added`
`entity_action_chosen`

Now the real weird one - when dying:
`entity_action_added`
`entity_action_removed`
`entity_action_lost`
`entity_action_added`
`entity_action_removed`
`entity_action_respawned`

If `remove` gets called when leaving a world then `added` should be called when joining it
And when dying it should only call `respawned`

**Comment by ChrysanthCow** [comment]
I'll be testing this one alongside the original Fabric version, and will be aiming for parity with that.
Thanks for bringing up that there may be inconsistencies with that.

**Comment by ChrysanthCow** [comment]
I've tested and everything is consistent with the Fabric version apart from Action on Respawned

You have made two errors when it comes to what's running.

## The corrections (Origins Forge)
When joining a world:
`entity_action_added`

(I can't blame you for this one, I only found it because of logs)

When respawning:
`entity_action_added`
`entity_action_removed`
`entity_action_respawned`

## Origins Fabric On Respawned
`entity_action_removed`
`entity_action_added`
`entity_action_respawned`

This is where the trouble comes in, as this is the imparity here.

**Comment by SiverDX** [comment]
I added logs to the powers so this event call chain definitely happened like this 

there might be some incompatibility with some other mod then I guess

**Comment by ChrysanthCow** [comment]
I did too, maybe you were reading prior logs for On Respawn?

**Comment by SiverDX** [comment]
definitely not

![image](https://github.com/EdwinMindcraft/origins-architectury/assets/22003703/06b2d38d-843b-449e-a4c8-0e0a36cb3af1)

![image](https://github.com/EdwinMindcraft/origins-architectury/assets/22003703/7da3c3fa-3beb-4315-8b02-cc9135b6ed14)

**Comment by ChrysanthCow** [comment]
Alright, that's incredibly strange that you were getting those results. I'd probably see if it's an incompatibility on your end.

**Comment by ChrysanthCow** [comment]
~~Okay, I think that I understand the issue now. Are you using a multiple?~~

Nevermind.

**Comment by SiverDX** [comment]
havent been using the mod for a while now, what i remember is that it was some illager origin from https://www.curseforge.com/minecraft/mc-mods/bucolic-origins

i added the different `origins:action_on_callback` types to one of the powers (i think `illagerteam`) to find the cause of some problem i had

(i saw the nevermind but maybe the info is relevant for something)

**Comment by ChrysanthCow** [comment]
That's fair, I'm currently resolving this issue with somebody else (see https://github.com/EdwinMindcraft/origins-architectury/issues/345). My guess is that another mod is recreating the player on respawn.

Thanks for the feedback, and I'll probably leave you to your business.
