### ISSUE TITLE
Power type Origins:ignore_water is completely non-functional

### ISSUE THREAD

**Issue by Alchemicdumbass** [EdwinMindcraft/origins-architectury#336]
I am aware that this has been reported in a previous report, however it hasn't been resolved since then (2022).
I am using forge 43.2.14 and the origins forge port 1.7.1.0 for minecraft 1.19.2.
This issue isn't being caused by any other mods I have running.
The logs don't show any errors or anything related to the power, so it has to be the power itself that is malfunctioning.
This power is very difficult to replicate with other powers, please fix this.

What I expected to happen: the power causes the player to sink in water as if it isn't there and is unable to swim.
What happened instead: The player interacted with water normally, swimming and moving at a speed that is effected by the water.

**Comment by NoarkTheGreat** [comment]
Yes this has happened to me too
