### ISSUE TITLE
origins causes mahoutsukai power consolidation to fail

### ISSUE THREAD

**Issue by StarWalker1** [EdwinMindcraft/origins-architectury#338]
the server seems to treat the mahoutsukai event for power consolidation as an origins power and the server sends this error: 
![image](https://github.com/EdwinMindcraft/origins-architectury/assets/44377596/d8bc91a9-9fec-4448-968f-bd5c0bdc9fd4)
the event fails and nothing happens when trying to create caliburn.
origins forge version: 1.19.2-1.7.1.0
mahoutsukai version: 1.19.2-1.34.46

**Comment by ChrysanthCow** [comment]
Duplicate of #322
