### ISSUE TITLE
[Question] Will this mod see continued support for Forge (1.20.1)

### ISSUE THREAD

**Issue by MrKashew** [EdwinMindcraft/origins-architectury#341]
Hate to be him but will this mod be updated to 1.20 seeing as the fabric counterpart has been updated?

**Comment by ChrysanthCow** [comment]
We talked about this in my Discord, but I will confirm for everybody else here.

Yes, the project is alive, I've recently become an extra maintainer for the project, expect 1.20.1 support once I fix bugs on 1.19.2.

**Comment by Darkmega18** [comment]
would that include backporting small fixes and patches if some bugs slip through the cracks after the point of which you commence the update...?

**Comment by ChrysanthCow** [comment]
> would that include backporting small fixes and patches if some bugs slip through the cracks after the point of which you commence the update...?

I don't see why not.

**Comment by Darkmega18** [comment]
:ok_hand: :+1:
basically, I just don't wanna get left behind without the potential for bug fixes in 1.19.2 if you've already gone to 1.20 while I'm making my modpack. although I'm sure most of it works...

**Comment by Reshirou** [comment]
> 👌 👍 basically, I just don't wanna get left behind without the potential for bug fixes in 1.19.2 if you've already gone to 1.20 while I'm making my modpack. although I'm sure most of it works...

I've been using Origins Forge on my 1.19.2 server for months now, and Origins is _never_ the cause of any breaking issues. I would not worry about it "losing support"!

**Comment by Darkmega18** [comment]
> I've been using Origins Forge on my 1.19.2 server for months now, and Origins is _never_ the cause of any breaking issues. I would not worry about it "losing support"!

_*[laughs nervously about my issue in the other thread about my start gear coming back constantly even though recurrent is set to false.]*_ You be lucky there. I get atleast a little bit of whack here and there until it gets figured out. dunno if cause me or it. the fun of fabric vs forge ports I guess.

**Comment by MrKashew** [comment]
I just saw the update you've put out - so exciting! Looking very much forward to when the version makes it to 1.20 🥳

**Comment by StormCircuit** [comment]
Any update on 1.20 progress? Even a "eventually"? It does not look like the repo has moved in a bit

**Comment by ChrysanthCow** [comment]
> Any update on 1.20 progress? Even a "eventually"? It does not look like the repo has moved in a bit

I'm having a break rn, I'm feeling a little burnt out. I will absolutely give an "eventually" though.

**Comment by ChrysanthCow** [comment]
1.20.1 will happen after 1.19.2 has Modify Player Spawn optimisations handled.

**Comment by Darkmega18** [comment]
> 1.20.1 will happen after 1.19.2 has Modify Player Spawn optimisations handled.

:O so theres still hope for my spawn locations for origins without lagging out the server and timing out everyone involved everytime someone new joins? cause it definitely didn't happen as badly in a similarly sized pack in 1.16.5 a lot of my mod bulk is micro additions and such which don't really generate much if at all. ._.

**Comment by rafucuk** [comment]
> 1.20.1 will happen after 1.19.2 has Modify Player Spawn optimisations handled.

well that means will origins 1.20.1 will come out soon or it have some couple weeks?

**Comment by MrKashew** [comment]
> > 1.20.1 will happen after 1.19.2 has Modify Player Spawn optimisations handled.
> 
> well that means will origins 1.20.1 will come out soon or it have some couple weeks?

I would like to know too but Pug will release it when they’re ready and have the time, they’re already doing us a favor by becoming a maintainer - seems close on the roadmap at least

**Comment by ChrysanthCow** [comment]
The optimisations are now in a pull request for both Apoli and Origins Forge.

I'll start on 1.20.1 at some point, but no promises as to if it's soon. As always, it'll target stable Forge, however, this time this is more of an important point because after that, 1.20.1 Forge is a weird point in Forge history, with the split of Forge and NeoForge.

We'll see where people end up with this one, im inclined to continue with NeoForge once it has breaking changes as thats where a majority of the previous team are and it seems to be where most modders will be heading. The mod's name will still be Origins Forge.

**Comment by ChrysanthCow** [comment]
If something as big as Create moves to NeoForge, I'd imagine that most will jump ship.

**Comment by Darkmega18** [comment]
Hopefully.

**Comment by ChrysanthCow** [comment]
Just finished AdditionalEntityAttributes Forge's 1.20.1 port, I'll start on Calio a tad later.

**Comment by ChrysanthCow** [comment]
Just got 1.20.1 booting up with only features required for it to function, I'll work on adding the remaining 1.19.3-1.20.1 features tomorrow.

**Comment by ChrysanthCow** [comment]
That's 1.19.3's remaining features done, I'm probably going to take a break for a bit as 1.19.4 is the largest when it comes to new features, with global power sets and all.

I also can't forget that in 1.20, Fabric's resource conditions became a thing used in Origins, so we'll be using Forge's equivalent.

**Comment by Darkmega18** [comment]
Sounds like you're going well then. :D

**Comment by MrKashew** [comment]
Thanks so much Pug, can’t wait!

**Comment by ChrysanthCow** [comment]
I'm updating everybody and saying that I'm now onto the final bugtesting stage.

I've already fixed like 3 bugs relating to the base origins content but I'm going to have to postpone bug hunting until tomorrow, mainly because I'm tired and I need some time to rest after being at this all day.

**Comment by ChrysanthCow** [comment]
# And that's 1.20.1 released. CurseForge is pending but I assume that they'll be quick.

Your datapacks may need updating between the two versions. Check the changelog for more info.

**Comment by Darkmega18** [comment]
> Your datapacks may need updating between the two versions.

ha, funny joke. I can't update my pack just like that without literally everything being updated too. and shifting gears to make a new pack in 1.20 takes a whole another mindset to see whats available and make something out of it.
But thank you for all your work, Pug. For everyone else who's less pedantic and does less heavy cross feature datapack editing who can just make a new pack just like that.

~~I'll take that 1.19.2 update to patch the spawn location loading lag if you have it tho. but it's fine if you don't.~~ _(I already made a concession and just gave quark/supplementary maps to the locations instead to save my poor server instadieing every time. and arguably it's better for groups playing cause they don't get zoomied a thousand blocks apart when they're meant to be playing together.)_

**Comment by ChrysanthCow** [comment]
Dw, the Modify Player Spawn change will come soon:tm:

**Comment by MrKashew** [comment]
> # And that's 1.20.1 released. CurseForge is pending but I assume that they'll be quick.
> Your datapacks may need updating between the two versions. Check the changelog for more info.

YEAH I’ll be trying this today, thanks for all your hard work Pug!

**Comment by MrKashew** [comment]
closing this ticket thanks!

**Comment by Thspooks** [comment]
> That's 1.19.3's remaining features done, I'm probably going to take a break for a bit as 1.19.4 is the largest when it comes to new features, with global power sets and all.
> 
> I also can't forget that in 1.20, Fabric's resource conditions became a thing used in Origins, so we'll be using Forge's equivalent.

Hey, are you still working on 1.19.3?  >.>

**Comment by ChrysanthCow** [comment]
> > That's 1.19.3's remaining features done, I'm probably going to take a break for a bit as 1.19.4 is the largest when it comes to new features, with global power sets and all.
> > I also can't forget that in 1.20, Fabric's resource conditions became a thing used in Origins, so we'll be using Forge's equivalent.
> 
> Hey, are you still working on 1.19.3? >.>

I'm not releasing a version for 1.19.3 or 1.19.4. Sorry.

**Comment by Thspooks** [comment]
> > > That's 1.19.3's remaining features done, I'm probably going to take a break for a bit as 1.19.4 is the largest when it comes to new features, with global power sets and all.
> > > I also can't forget that in 1.20, Fabric's resource conditions became a thing used in Origins, so we'll be using Forge's equivalent.
> > 
> > 
> > Hey, are you still working on 1.19.3? >.>
> 
> I'm not releasing a version for 1.19.3 or 1.19.4. Sorry.

Ahh okay yeah thats understandable, i just saw 1.19.3 and i just hoped i could use this with magma for server, but ill stick to 1.19.2 then  >.> I heard theres alot of differences between 1.19.2 and 1.19.3 so i understand that too well
