### ISSUE TITLE
`ability` entity condition type crashes world startup

### ISSUE THREAD

**Issue by ChrysanthCow** [EdwinMindcraft/origins-architectury#342]
I don't have the proper logs for this atm, but this is something that I've tested.

**Comment by LizzieSpace** [comment]
I do believe i might be running on a similar issue, this time regarding extreme inconsistencies regarding ability init that seem to be. i've ran on plenty of issues of that kind especially with origins++
here follows a segment of the crash logged: [on pastebin](https://pastebin.com/raw/44buXaCq)
the problems on Apoli happen regardless of origins++ presence

**Comment by LizzieSpace** [comment]
May also be related to #324, #330, #323...

**Comment by ChrysanthCow** [comment]
You seem to have 3 bugs in one, so it's hard to find from your logs. But I'm going to source the ability bug now.

**Comment by ChrysanthCow** [comment]
The issue is:
- The implementation was unfinished.
- The names of the abilities were not the same as the Fabric version.
- There was no error catching inside the data type.
