### ISSUE TITLE
Move away from CurseMaven

### ISSUE THREAD

**Issue by ChrysanthCow** [EdwinMindcraft/origins-architectury#344]
This is a planned change that I will make sometime during the next release.

Origins Forge and its contemporaries will be hosted on maven.merchantpug.net going forth.

JitPack will be available as an option but it won't be the main repository.

**Comment by Thspooks** [comment]
Out of curiosity, that means you are helping/took the main dev role of forge origins port? >.>

**Comment by ChrysanthCow** [comment]
> Out of curiosity, that means you are helping/took the main dev role of forge origins port? >.>

I am not the main dev, but I am helping.

Edwin was contacted and agreed regarding this change

**Comment by Thspooks** [comment]
Oh ok thats amazing! Im glad this man got help with this port c: Im looking forward to see how the port goes!
