### ISSUE TITLE
Any kind of reach not working as intended (?) 

### ISSUE THREAD

**Issue by Thspooks** [EdwinMindcraft/origins-architectury#348]
I were excited to see the patch fix out, thus i started porting certain origin for personal/private use. Mod is attempting to read the file containing reach modifiers, but it seems it doesnt entirely "knows" what it is. Thought its worth posting >.> 
im attaching the power file too. If i forgot to post something important, please let me know! ill do it

`Power "armor:extra_reach" will only be partially loaded: At Attribute: Identifier "reach-entity-attributes:attack_range" was not registered in registry "minecraft:attribute".; At Attribute: Identifier "reach-entity-attributes:reach" was not registered in registry "minecraft:attribute".`

**Comment by Thspooks** [comment]
https://pastebin.com/Vh29qgep
I did not realized github doesnt supports json >.>

**Comment by ChrysanthCow** [comment]
Hi, the reach attribute is handled differently in this port as Forge has built-in attributes for these two attributes. You'll have to use `forge:block_reach` and `forge:entity_reach`. instead of the two you have there.

**Comment by Thspooks** [comment]
Im not sure if im doing something wrong, but it doesnt works nonetheless
https://pastebin.com/YCUEGvV5

**Comment by ChrysanthCow** [comment]
You have a JSON parsing error judging by the two images. Remove the comma near the `]` and you should be good.

**Comment by Thspooks** [comment]
I digged a bit on origins server, and ive found an old thread to use `forge:reach_distance` and that worked to be fair. The code i sent is a part of a bigger code.

**Comment by ChrysanthCow** [comment]
> I digged a bit on origins server, and ive found an old thread to use `forge:reach_distance` and that worked to be fair. The code i sent is a part of a bigger code.

Ah, yeah, you might be on an older version. Forgot about that.
