### ISSUE TITLE
Crash on server during setup (1.19.2)

### ISSUE THREAD

**Issue by Thspooks** [EdwinMindcraft/origins-architectury#352]
Hello, i wanted to make a server for me and my friends using forge mohist (38), but im encountering a crash with origins. If this is caused not by origins, but by mohist then im sorry, please let me know and ill delete this thread and redirect it to them. im using newest version (1.7.12), but i think it happenes with .11 too 

If i missed some important information, ill gladly give it.

https://pastebin.com/QgQMzCcy

**Comment by Thspooks** [comment]
This happenens on arclight too.

**Comment by ChrysanthCow** [comment]
Please update Obscure API, I think that this has been fixed on their end.
