### ISSUE TITLE
craftable orb of origin 

### ISSUE THREAD

**Issue by BONEWEEVIL1** [EdwinMindcraft/origins-architectury#356]
how do i make the orbe non craftable im in 1.18.2

**Comment by Illios42** [comment]
You can use a mod like CraftTweaker to remove recipes. That's honestly not a question you should be spamming here in the issue reports though, so maybe close your tickets and ask on the Origins/a modding Discord next time.

**Comment by ChrysanthCow** [comment]
Duplicate of #354, which was also asked.

> You can use a mod like CraftTweaker to remove recipes. That's honestly not a question you should be spamming here in the issue reports though, so maybe close your tickets and ask on the Origins/a modding Discord next time.

Illios42 said it best.
