### ISSUE TITLE
Origins with multiple abilities activate all of them on using Primary Ability keybind

### ISSUE THREAD

**Issue by BlackjackMKV** [EdwinMindcraft/origins-architectury#357]
(Created new issue for visibility reasons.)

While ya'll definitely aren't obligated to, I would *love* to see a backport for 1.18.2 with the issue of all abilities activating on primary ability fixed since there isn't a build for 1.18.2 without this bug. Given the size of it and how popular 1.18.2 is as a version for modding, it would be greatly appreciated.

And, to clarify, I'm not asking for ongoing support for 1.18.2. I don't expect anyone to support an out of date version, of course. Rather, this bug is just massively debilitating to the point that I would love to see at least a single version released for 1.18.2 to fix it. There are a LOT of mods that haven't updated past 1.18.2, which means that a lot of people like my friend group don't have the option to simply update to 1.19+, on top of the many questionable decisions Mojang is making in 1.19.1+ onwards(such as the report system) making it generally not a great idea for even vanilla users to update. Basically, lots of users either can't because of mod issues or won't because of Mojang doing dumb things, and therefore I feel like just one update to fix this issue would be extremely well received.

_Originally posted by @BlackjackMKV in https://github.com/EdwinMindcraft/origins-architectury/issues/235#issuecomment-1680419838_

**Comment by BlackjackMKV** [comment]
If that's not something you're willing to do, I entirely understand and you can go ahead and just close the ticket. It would be immensely helpful though!

**Comment by ChrysanthCow** [comment]
I'll probably get around to a major 1.18.2 bugfix at some point in the future as the final version, I'm just wanting to get 1.20.1 out first.

**Comment by BlackjackMKV** [comment]
Sounds good! Thanks for the reply! I'll just warn players then about the issue like I have been until that's done. Feel free to take your time as well. I'm just glad to know it'll most likely happen at some point. :)

**Comment by Deathwarp6** [comment]
This is great news! I have been trying to play 1.18.2 lately, and I just can get any of my origins to work at all. I phase when I try to float, blow up when I try to phase, and so on. As previously mentioned though, 1.20.1 is more pertinent at the moment.

**Comment by Deathwarp6** [comment]
Just curious, how far along is this currently?

**Comment by ChrysanthCow** [comment]
> Just curious, how far along is this currently?

Haven't started. 1.18.2 also needs a ton of rewriting, so it's difficult to just do it.

**Comment by Deathwarp6** [comment]
I understand, I do some light coding and it's a pain so I can't imagine a mod this vast. Thanks for the feedback though, lets me know the devs care.

**Comment by MaverickMartyn** [comment]
I'm so relieved to hear that it's in the works!
I just encountered this bug while building my 1.18.2 pack, and I'm unfortunately stuck on 1.18.2 for numerous reasons.
Thank you for your work! :)

**Comment by BlackjackMKV** [comment]
Has this been fixed yet by any chance? It's fine if not, I just thought I'd check in on this since, checking the changelogs in the other versions released since I posted this, I don't see a fix for it yet.

**Comment by ChrysanthCow** [comment]
> Has this been fixed yet by any chance? It's fine if not, I just thought I'd check in on this since, checking the changelogs in the other versions released since I posted this, I don't see a fix for it yet.

This is a 1.18.2 change, I've only been working on 1.20 atm.
Keep in mind that I'm doing this as a hobby, and 1.18.2 has many other issues that I'd have to look into before I get to releasing a version, it's honestly kinda overwhelming to have to put all this work into a version of the game that I don't super care about (no offense).

**Comment by BlackjackMKV** [comment]
> > Has this been fixed yet by any chance? It's fine if not, I just thought I'd check in on this since, checking the changelogs in the other versions released since I posted this, I don't see a fix for it yet.
> 
> This is a 1.18.2 change, I've only been working on 1.20 atm. Keep in mind that I'm doing this as a hobby, and 1.18.2 has many other issues that I'd have to look into before I get to releasing a version, it's honestly kinda overwhelming to have to put all this work into a version of the game that I don't super care about (no offense).

No worries! As I mentioned earlier, I'm just glad it's even a consideration. If it wasn't for this lovely 1.1984 update that has been banning people for cussing in their own private LAN worlds even, I'd probably be on the latest version anyway. Between that and the fact they've not added anything I particularly care about with WAY more mods on 1.18.2 than on 1.19+, I just haven't wanted to or cared to update. Since it's very much my choice to stay on an out of date version though, I don't expect any continuing support, so I'm just happy you're even considering doing it at all. :)
