### ISSUE TITLE
Bound must be positive crash

### ISSUE THREAD

**Issue by Thspooks** [EdwinMindcraft/origins-architectury#360]
From what i know the way how origins is changing phantom spawn is causing a server crash (arclight) at random 
[crash-2023-09-05_02.21.58-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/12537327/crash-2023-09-05_02.21.58-server.txt)
Modlist is included along with crashlog

**Comment by ChrysanthCow** [comment]
Just fixed this in 1.20, will fix it in 1.19 alongside the Modify Player Spawn optimisations.

**Comment by ChrysanthCow** [comment]
Will be closed once I fix this in a 1.19.2 version.

**Comment by Thspooks** [comment]
Thank you for all the work. Im really grateful
