### ISSUE TITLE
Issue with ability in Fox Origin Datapacks (1.20.1)

### ISSUE THREAD

**Issue by PostoapocalMaster** [EdwinMindcraft/origins-architectury#363]
Version 1.20.1. The jump ability does not work correctly in datapacks like Spirit Fox and recreation of Fox origin from ORIGIN SMP. It sends you in a random direction instead of the one you're looking at.

Datapacks: 
https://drive.google.com/file/d/1jnleXoMD-jVUbANPjRZlbqI3dV8O7XlL/view?usp=sharing
https://drive.google.com/file/d/19dgD-GRDsPQ3ZhkRd9zQjGGDmby3C5KB/view?usp=sharing

**Comment by ChrysanthCow** [comment]
Fixed, I've also gone and fixed another issue that I found with Origins Forge where the `phase_down_condition` being unset in the phasing power would make you fall through the world unconditionally.

**Comment by PostoapocalMaster** [comment]
> Fixed, I've also gone and fixed another issue that I found with Origins Forge where the `phase_down_condition` being unset in the phasing power would make you fall through the world unconditionally.

Thank you very much, now everything works correctly!
