### ISSUE TITLE
Origins forge causes a crash when a spell from mahou tsukai kills something

### ISSUE THREAD

**Issue by Alexo6o5** [EdwinMindcraft/origins-architectury#364]
[crash-2023-09-15_18.48.49-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/12623104/crash-2023-09-15_18.48.49-server.txt)

**Comment by ChrysanthCow** [comment]
This is caused by the Additional Entity Attributes Forge port, which is included in Origins Forge.

We also maintain that, so the fix will be done over there.

**Comment by ChrysanthCow** [comment]
We were just using an `getParam`, which throws if it's not there instead of `getParamOrNull`, which returns null if not present (the expected behavior).

Fixed for next update!
