### ISSUE TITLE
the forge thing

### ISSUE THREAD

**Issue by sirseraphim** [EdwinMindcraft/origins-architectury#37]
it sais i need forge 36.1.3 or above but I cant download it I need a version that can download with forge 36.0.1

**Comment by EdwinMindcraft** [comment]
Download it [here](https://files.minecraftforge.net/net/minecraftforge/forge/). Forge 36.1.3 is here due to compatibility concerns with another mod, Downgrading is not an option. If your launcher cannot handle Forge 36.1.3 or greater, please consider changing either updating or outright changing your launcher of choice.

**Comment by sirseraphim** [comment]
> Download it [here](https://files.minecraftforge.net/net/minecraftforge/forge/). Forge 36.1.3 is here due to compatibility concerns with another mod, Downgrading is not an option. If your launcher cannot handle Forge 36.1.3 or greater, please consider changing either updating or outright changing your launcher of choice.

probleme is I use tlauncher

**Comment by EdwinMindcraft** [comment]
Their inability to update is none of my concern. They should already have Forge 36.1.32 available. If they don't, that's not on me, that's on them. Origins CANNOT be safely downgraded to forge 36.0.1, especially considering that this version is a **BETA** and that any version before 36.1.0 isn't considered stable. The number of breaking bugs fixed between 36.0 and 36.1 is large enough for me to say that playing on 36.0.1 isn't something that I want to support.

This gives you two choices:
* Ask the owners of tlauncher to update their Forge version.
* Use CurseForge, MultiMC or the standard Minecraft launcher, as those are the ones I know will support the required version of Forge.
