### ISSUE TITLE
[1.20.1 Forge] Scroll / additional info appearing randomly

### ISSUE THREAD

**Issue by MrKashew** [EdwinMindcraft/origins-architectury#371]
Having this very strange bug where when I first join my server at times I will not be able to see further information about an origin (no scroll etc)

![image](https://github.com/EdwinMindcraft/origins-architectury/assets/53996665/751c41a6-bbc0-4e2b-a669-8b879a24546e)

but upon kicking + rejoining I can see it

![image](https://github.com/EdwinMindcraft/origins-architectury/assets/53996665/2a3cda2b-3a96-448e-a18a-d79835a94920)

[debug.log](https://github.com/EdwinMindcraft/origins-architectury/files/12706268/debug.log)
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/12706269/latest.log)

I tried this without Origins++ (and XL packets) and was receiving this issue - so not sure what could be the cause yet

**Comment by ChrysanthCow** [comment]
I swore that I fixed this during dev-time. wtf.

**Comment by ChrysanthCow** [comment]
I forgot to handle this this patch, but this patch was sorta split into 2 patches anyways, so you're in luck.

**Comment by Thspooks** [comment]
Having same bug on 1.19.2, on newest version for it

**Comment by ChrysanthCow** [comment]
Fixed for next 1.20.1 update.

**Comment by ChrysanthCow** [comment]
Basically the 🤓 rundown is two things.

1. We sorted a set for syncing to the client, but we didn't set it to be an actual sorted set, so the sorting meant nothing.
2. Even if the above was the case, the check for if there's a loading order wasn't what it should've been, so everything would've output -1 in the sort (basically meaning random order).

**Comment by ChrysanthCow** [comment]
If anybody is still running into this, it may be fixed with the registry fixes.
