### ISSUE TITLE
Clientnbts stored in the wrong place

### ISSUE THREAD

**Issue by TheKaratCake** [EdwinMindcraft/origins-architectury#375]
I'm no expert on this but apparently in the fabric version certain nbts are stored in playerdata, not having that breaks just, so much and is making me do a lot extra work, please can you fix this

**Comment by ChrysanthCow** [comment]
What exactly do you mean by this?
If you're saying that ForgeCaps and cardinal_components should be the same, unfortunately that's something that shouldn't be fixed because we should be using standardised Forge things when possible to ensure compat, even if there is a minor difference.

**Comment by TheKaratCake** [comment]
Well, my example is that the mod figura cannot communicate with origins on forge but can with origins on fabric due to where something is stored, some form of data, the quote from the person who was explaining this to me is as follows: "figura cannot access random data. The only reason this works is because official origins graciously puts all it's data into a common data area: player nbt"

**Comment by ChrysanthCow** [comment]
> Well, my example is that the mod figura cannot communicate with origins on forge but can with origins on fabric due to where something is stored, some form of data, the quote from the person who was explaining this to me is as follows: "figura cannot access random data. The only reason this works is because official origins graciously puts all it's data into a common data area: player nbt"

Origins Forge should too. I don't have access to my pc atm, but search through the ForgeCaps nbt tag.
The location won't be changed because of loader differences, but, Origins are stored in player nbt here too.

**Comment by ChrysanthCow** [comment]
This should probably be written somewhere though

**Comment by TheKaratCake** [comment]
Yeah sorry I don't now what else to tell you other than it doesn't work with forge origins

**Comment by ChrysanthCow** [comment]
Must be desync then. I think I understand this now.

**Comment by TheKaratCake** [comment]
I hope so, can you make sure theres a 1.19.2 version with it fixed, that's really important for my like, everything

**Comment by ChrysanthCow** [comment]
`/data get entity @s ForgeCaps`
![image](https://github.com/EdwinMindcraft/origins-architectury/assets/81167232/c4f8901e-3b76-4c7c-b8c8-98592a512b16)

This screenshot is on 1.20.1, but it should be the same on 1.19.2.
