### ISSUE TITLE
origins:modify_air_speed does not seem to be working

### ISSUE THREAD

**Issue by BleachKing919** [EdwinMindcraft/origins-architectury#378]
While origins:modify_air_speed is able to make entities go faster, I cannot get it to make entities slower than normal while flying, falling, or doing really anything in the air.

**Comment by ChrysanthCow** [comment]
Will take a look when possible

**Comment by ChrysanthCow** [comment]
Which origins forge version btw?

**Comment by BleachKing919** [comment]
Any version that seems to be post 1.20
