### ISSUE TITLE
Reducing mining speed with origins:modify_break_speed power doesnt let you break instabreak blocks

### ISSUE THREAD

**Issue by liopyu** [EdwinMindcraft/origins-architectury#379]
This is with any item, not just the diamond shovel used in the video.

Version: 1.19.2 - 1.17.1.2

![ezgif com-video-to-gif (6)](https://github.com/EdwinMindcraft/origins-architectury/assets/130418550/43e58418-600f-4552-b8b2-6a78de905abd)

"breakspeed": 
    {
      "type": "origins:modify_break_speed",
      "modifier": {
          "operation": "multiply_base",
          "value": -0.15
      }
  }

**Comment by ChrysanthCow** [comment]
This is also an issue with Origins Fabric. I'd suggest reporting it over there, we'll get to it when it's fixed over there.

**Comment by ChrysanthCow** [comment]
I'll report it over there for you.

**Comment by liopyu** [comment]
thanks, ive been so busy this week i didnt even see your message til now

**Comment by ChrysanthCow** [comment]
@liopyu Here's a workaround for the time being if you're still having troubles with this.
https://github.com/apace100/apoli/issues/170#issuecomment-1848987554

**Comment by liopyu** [comment]
thank you, i ended up using a modded's mining attribute from puffish skills mod though i will keep this in mind! @MerchantPug
