### ISSUE TITLE
/reload failed (1.20.1)

### ISSUE THREAD

**Issue by coucoul38** [EdwinMindcraft/origins-architectury#380]
When I do /reload it says "Reload failed; Keeping old data."
I looked at the logs and it seems to be an issue with the mod

When I save and restart the world, my datapack is loaded as expected.

Here's the relevent part of the log:
[reload failed log.txt](https://github.com/EdwinMindcraft/origins-architectury/files/13033502/reload.failed.log.txt)

**Comment by coucoul38** [comment]
How do I add a label ?

**Comment by ChrysanthCow** [comment]
ah. I must've forgotten to register that packet.

I'll have a fix out sometime in the future.
