### ISSUE TITLE
Origins mod completely blocks Curious UI in inventory and ruins all mods that use curios

### ISSUE THREAD

**Issue by Kryllex** [EdwinMindcraft/origins-architectury#381]
As the title says with this mod (latest 1.20.1 version) Curious UI button in inventory does not open the curios UI, it opens the same vanilla inventory with a slight shifting/moving of regular elements/buttons. Bricks my modpack and only solution is to remove origins mod.

**Comment by ChrysanthCow** [comment]
Strange issue... I'm unsure what would be causing this, definitely a high priority thing to fix though.

**Comment by Kryllex** [comment]
Just wanted to add it is replicable with just the 2 mods alone in 47.2.0 forge

**Comment by ChrysanthCow** [comment]
This is most likely caused by a keybind conflict, I changed my keybind in the settings in an attempt to make sure it wasn't replicable.

Please change your keybinds and reopen this issue if that was the issue.
