### ISSUE TITLE
Cannot launch server with Origins installed.

### ISSUE THREAD

**Issue by StuffOfSonny** [EdwinMindcraft/origins-architectury#383]
Spent two entire days going one by one with a mods list my friends put together to determine why thee server wasn't launching, and I eventually narrowed it down to Origins.

I have no idea what to make of the console output, so I'm going to attach my latest.log
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/13171996/latest.log)

**Comment by ChrysanthCow** [comment]
Unfortunately, there is no crashlog within this file. May you please share the latest file inside the `crash-reports` folder?

**Comment by StuffOfSonny** [comment]
Long story short I cleaned out all of the pre-origins crash reports, and ran the server in an attempt to generate a crash report, but for some reason it's not giving me any.

**Comment by StuffOfSonny** [comment]
I re-ran the server, still no crash report, but I copied the extra lines in the console that do not show up in the latest.log, and I hope it can be of use
[manual-report.txt](https://github.com/EdwinMindcraft/origins-architectury/files/13182453/manual-report.txt)

**Comment by ChrysanthCow** [comment]
hmm, this is a crash, although I can't see anything pointing towards us being the cause, could you send the **full** logs for that? There's not enough context here.

**Comment by EdwinMindcraft** [comment]
L10 of the crash log tells me this is Mohist (an hybrid spigot/forge server). While it usually works well with most mods origins has **significantly** more mixins and coremods than most mods.
Right now, from the limited information we have, the most likely is that a coremod failed to apply since a class is missing (Mixin usually fails either silently or with an actual error message).

**Comment by ChrysanthCow** [comment]
Ah, I didn't know what Mohist was. Thanks Edwin.

**Comment by StuffOfSonny** [comment]
I opted to go with Mohist as it made installing mods to a spigot server as easy as installing plug-ins. I'm willing to try something else if it can be explained to me like I'm 5. Ease of use goes a long way.

Edit - alternatively, I can send basically whatever information you ask for to see if there's any way to get Mohist working.

**Comment by StuffOfSonny** [comment]
For the time being, I have swapped over to Forge. While I would much prefer the option of running additional plug-ins, it's gonna come down to either this issue being resolved, or for Sponge/Magma/Cat to update to 1.20

**Comment by ChrysanthCow** [comment]
> For the time being, I have swapped over to Forge. While I would much prefer the option of running additional plug-ins, it's gonna come down to either this issue being resolved, or for Sponge/Magma/Cat to update to 1.20

I don't think this is within our power to fix unfortunately. As Edwin described it, Mohist probably changes the location of MC internals that we need.
