### ISSUE TITLE
POV bug

### ISSUE THREAD

**Issue by hroudland** [EdwinMindcraft/origins-architectury#385]
there's an issue on the 1.20.1 version of origins where when you select an origin that changes your POV (i.e. pixie or dwarf), the pov doesn't change/reflect on the size of the playermodel.

**Comment by ChrysanthCow** [comment]
This is not a base Origins Forge feature.

You're likely using Pehkui (a library) for the size changing. Would you mind if you send me the data pack, I have a suspicion as to why it might not work.

**Comment by hroudland** [comment]
Sorry I mistook it for this mod，I added pehkui in ATM9 and mod loading but commands not working in forge.
