### ISSUE TITLE
currently experiencing an issue when it comes down to joining an existing worlds in multiplayer (1.20.1)

### ISSUE THREAD

**Issue by EeriShimi** [EdwinMindcraft/origins-architectury#387]
having an issue in a line of code in the library 
Error in log:
https://paste.essential.gg/rAKUf1z3wT#L28223
Line in source code where the error is: 
https://github.com/EdwinMindcraft/calio/blob/1.20.x/forge/src/main/java/io/github/edwinmindcraft/calio/common/registry/CalioDynamicRegistryManager.java#L279
when playing on the curseforge modpack "The M.Meows pack" and joining a new world I would not be able to join properly, and if I did it would crash quite often
if you need more information I can give debug logs and such

**Comment by ChrysanthCow** [comment]
Fixed for next update.
