### ISSUE TITLE
[1.20.1] Default origin layer cannot be replaced by a custom origin

### ISSUE THREAD

**Issue by Reniel80** [EdwinMindcraft/origins-architectury#393]
Custom origin `replace` is set to `true` and `order` 0 and In game, at selection window... they are stilll appended to default ones.

**Comment by ChrysanthCow** [comment]
Could you send the datapack here for testing purposes?

**Comment by Reniel80** [comment]
Yup! remember it's a datapack in a jar and i found all issues when i load it as a mod not as datapack.
i cannot upload a jar file here, is not supported, so i will change manually the extension to zip. please rename it to jar when you download it.
[Legendary Origins 1.2311.1.zip](https://github.com/EdwinMindcraft/origins-architectury/files/13626166/Legendary.Origins.1.2311.1.zip)

**Comment by ChrysanthCow** [comment]
Incredibly strange. I can't seem to replicate this in my environment.

My guess is that the base origins have a chance of being loaded *after* your datapack. So my suggestion would be to plop a `loading_priority` onto it.

This'd look like

```
{
  "loading_priority": 1,
  "origins": [
    ...
  ],
  ...
}
```
