### ISSUE TITLE
1.18.2 Support

### ISSUE THREAD

**Issue by Lilwhiteshark** [EdwinMindcraft/origins-architectury#394]
Hi! I was going to make several bug reports but it looks like they're already tracked. 

Is `[1.18.2] Origins Forge 1.5.0.1` still supported?
If so, could I request a backport to 1.18.2 of the fixes brought to the `[1.19.2] Origins Forge 1.7.1.1` version of the mod? (or the latest version if possible).

I appreciate all of your work! :)

**Comment by ChrysanthCow** [comment]
I'm probably going to touch it again eventually, It's just that I'm busy, and 1.18.2 is actually more huge of an undertaking than you'd think.

**Comment by D0ppleganger** [comment]
well its nice to know its already being looked at later, thank you for that
