### ISSUE TITLE
lost water night vision 1.19.2

### ISSUE THREAD

**Issue by Aceplante** [EdwinMindcraft/origins-architectury#396]
I was playing merfolk and randomly lost my underwater nightvision. I still seem to have my water breathing, but i appear to have normal water vision? So I restarted my game and it didnt help.

forge 1.19.2

**Comment by Aceplante2** [comment]
Edit, and now its back again?

**Comment by ChrysanthCow** [comment]
Try pressing the Primary Active key. (Defaulted to G) You may have accidentally pressed it.

**Comment by Aceplante** [comment]
ah keybind conflict thank you
