### ISSUE TITLE
1.20.1 Eventual Bulk Crafting Crashes on Server

### ISSUE THREAD

**Issue by tgarr0** [EdwinMindcraft/origins-architectury#397]
When crafting large numbers of items repeatedly, the server will crash (leaving only the reader-unfriendly Java crashlog). This is most easily replicated by crafting ingots to and from nuggets.
Tested using Forge 47.2.0, Origins 1.10.0.2, and Caelus 3.1.0+1.20.
(Crash does not occur with Forge alone.)
Could be tangentially related to #374.
Side note: FastWorkbench seems to solve this problem without interfering with origin-specific recipes.

**Comment by ChrysanthCow** [comment]
You are probably right in that it's related to #374, I'll look into a fix the next time I touch Origins Forge.
