### ISSUE TITLE
[GAME BREAKING] 1.20.1 Origins invalidating item Capabilities

### ISSUE THREAD

**Issue by briarss** [EdwinMindcraft/origins-architectury#398]
To add on to #395 , any mod that has item capabilities has their capability seemingly nullified and reset whenever it enters a players inventory. Tested with Iron Jetpacks and TerraFirmaCraft (Unsealed barrels, lamps, water jugs all default to empty. Weirdly, sealed barrels dont change.)

This is a major **game breaking** bug that means Origins forge cant really be used.

**Comment by ChrysanthCow** [comment]
I think that I know the culprit code, it couldn't be anything else.

**Comment by ChrysanthCow** [comment]
Fixed for upcoming update.
