### ISSUE TITLE
[1.20.1] Orb of origin not visible in gui.

### ISSUE THREAD

**Issue by Thspooks** [EdwinMindcraft/origins-architectury#400]
Its simply not in gui, but available trough /give . Using version 1.20.1-1.10.0.4
Is that a bug or intentional? In case ill provide logs or something, but i dont think i need to as i saw alot of people having this issue. Im just posting it here to hopefully know why its not here

**Comment by Thspooks** [comment]
Also it seems /origins command wont work serverside? But im not 100% sure if this is incompability or something. I dont wanna make baseless assumptions

**Comment by ChrysanthCow** [comment]
Ah, this is the first time I actually have heard of this.
I think I just forgot to include it in the creative menu.

**Comment by ChrysanthCow** [comment]
I'll release a fix for this sometime soonish.
