### ISSUE TITLE
Disconnect when reloading

### ISSUE THREAD

**Issue by Puggicorn** [EdwinMindcraft/origins-architectury#403]
Error message:
"Illegal packet received, terminating connection"

Tested on latest neoforge version for 1.20.1 and latest Origins-Forge 1.10.0.4

**Comment by ChrysanthCow** [comment]
I think that this happens when you have errors in your datapack. This might be something that I'll go in and fix before the NeoForge rewrite.

**Comment by Puggicorn** [comment]
Tested again on a fresh install with all the latest versions. Here is a log of loading into a word, and then reloading:
https://mclo.gs/MjMwSGf

It appears that it is caused by whatever runs after the advancements load in, but that is all I could really get from it.

**Comment by ChrysanthCow** [comment]
Fixed. I accidentally marked a packet as client to server when it's actually server to client.
