### ISSUE TITLE
"Internal exception"when trying to generate a new world or join an existing one

### ISSUE THREAD

**Issue by euquinox** [EdwinMindcraft/origins-architectury#405]
hi! I keep getting this error whenever I am trying to generate a new world or join an existing one

Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root/apoli:configured_power] was missing

[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/13930233/latest.log)

**Comment by Xplodin** [comment]
yup also getting this error. Are you using origins++ by any chance?
