### ISSUE TITLE
Game crashes when using Origin command inside of /execute

### ISSUE THREAD

**Issue by ryleu** [EdwinMindcraft/origins-architectury#408]
![image](https://github.com/EdwinMindcraft/origins-architectury/assets/69326171/fba50cbd-ac6c-4b26-986d-ab712f448a82)
https://mclo.gs/B1MQKwl 

Origins v1.20.1-1.10.0.5 
Caelus API v3.1.0+1.20
Forge v47.2.0
Minecraft v1.20.1

Reproduced crash with just Origins and its dependencies. 
``` 
/scoreboard objectives add origins dummy   
/execute store success score @s origins run origin has @s origins:origin -> (hit tab here)
```

**Comment by ryleu** [comment]
It seems to be a brigadier issue, so that basically means the parser doesn't know what to do with your command.

**Comment by ChrysanthCow** [comment]
I've implemented a partial fix for this similar to the one found in Origins Fabric. Suggestions will not work for Origins inside `/execute`, but at least it doesn't crash.
