### ISSUE TITLE
Unknown Registry Key modify_enchantment_level

### ISSUE THREAD

**Issue by muon-rw** [EdwinMindcraft/origins-architectury#409]
When trying to add a power using modify_enchantment_level, it does not load giving the error in the title. 

Is this power type not yet ported to Origins Forge?

Using origins-forge-1.20.1-1.10.0.5

**Comment by ChrysanthCow** [comment]
Modify Enchantment Level was introduced in a later version, this means that either:

1. eggo's plan on backporting the 1.20.2 updates happens.
2. This won't be coming to 1.20.1, but will be present in later versions.
