### ISSUE TITLE
Possible Incompatability

### ISSUE THREAD

**Issue by PosingCarton** [EdwinMindcraft/origins-architectury#413]
When using Embeddium the origin selection menu does not show up, and when pressing "o" to view an origin it says, "You cannot have an origin".

While trying to replicate to make sure it is consistent I got the error "Internal Exception: java.lang.IllegalArgumentException: Registry ResourceKey[minecraft:root / apoli:configured_power] was missing. Upon a second launch the world worked, just without the orgin menu

(1.20.1  Forge-47.2.0)
(Embeddium Version 0.2.18)
(Origins Version 1.10.0.5)
(Origins addons: Origins++, Origins Classes)

**Comment by hammy275** [comment]
Want to corroborate this. Unless it's just luck, removing Xenon (an Embeddium fork) fixed this exact `IllegalArgumentException` error. No idea why one is impacting the other.

On Minecraft 1.20.1 with Forge 47.2.17 and Origins version 1.10.0.5. 

To be more specific about other mods I have, I'm playing a slightly modified version of Medieval MC [Forge] MMC4 v25.

**Comment by ChrysanthCow** [comment]
I'm unsure why Embeddium would cause this of all mods, it just shouldn't affect this part of the code, That's incredibly weird.

I'd imagine that it's moreso an issue with Origins Forge itself.

The thing is, that the registry system for Origins Forge has been kinda hacky for a while now, and the consensus that I've kinda come to with it is that it's probably only 100% fixable once we move over to NeoForge and hook into vanilla registration.
