### ISSUE TITLE
in_tag Damage condition doesn't exist (1.20 1.10.0.5)

### ISSUE THREAD

**Issue by muon-rw** [EdwinMindcraft/origins-architectury#414]
Trying to use this damage condition at all results in the condition failing to load with `Unknown registry key: origins:in_tag`

This feature exists in 1.10.0 for Origins Fabric. 

~~Looking at the condition/damage package in Apoli Forge, it looks like this was just never added.~~
I am blind, but for some reason I _am_ getting this error.

**Comment by muon-rw** [comment]
Looks like the condition type was created, but simply not registered.

**Comment by ChrysanthCow** [comment]
Will fix next update, thanks for looking into it.

**Comment by Cynic1254** [comment]
I am having the same issue for origins:type as well (I haven't looked through the code but I am getting the exact same error as when using in_tag) any idea when this will be fixed?

**Comment by ChrysanthCow** [comment]
> I am having the same issue for origins:type as well (I haven't looked through the code but I am getting the exact same error as when using in_tag) any idea when this will be fixed?

I don't remember an `origins:type` existing. Could you please link me it on the docs?

**Comment by Cynic1254** [comment]
> > I am having the same issue for origins:type as well (I haven't looked through the code but I am getting the exact same error as when using in_tag) any idea when this will be fixed?
> 
> I don't remember an `origins:type` existing. Could you please link me it on the docs?

https://origins.readthedocs.io/en/latest/types/damage_condition_types/type/

**Comment by muon-rw** [comment]
> > > I am having the same issue for origins:type as well (I haven't looked through the code but I am getting the exact same error as when using in_tag) any idea when this will be fixed?
> > 
> > 
> > I don't remember an `origins:type` existing. Could you please link me it on the docs?
> 
> https://origins.readthedocs.io/en/latest/types/damage_condition_types/type/

This damage condition type was added after Origins 1.10, and is 1.20.2+ only on Fabric.
