### ISSUE TITLE
Featherweight enchantment does not work on armor. Any armor enchanted with it remains too heavy to equip for Elves

### ISSUE THREAD

**Issue by BobtheBromosapien** [EdwinMindcraft/origins-architectury#415]
I tested multiple variables such as modded vs base game armor pieces. Attempting to equip the armor as an Elf vs Non-Elf.
In every instance, all armor classified as too heavy to wear with the enchantment was unable to be equipped due to its restriction still being present. Every piece was able to be equipped by a Non Elf Race like Human after switching. This leads me to believe it is 100% an issue with the enchantment simply not doing anything/working.

**Comment by ChrysanthCow** [comment]
This is not an issue with the base Origins Forge mod, please report it to the corresponding addon.
