### ISSUE TITLE
it fixed itself after a while. 

### ISSUE THREAD

**Issue by armani2005Evil** [EdwinMindcraft/origins-architectury#417]
![image](https://github.com/EdwinMindcraft/origins-architectury/assets/159209374/c667719c-f8b8-4256-ac04-e7efb40c9a9b)

So, I was trying to get my origin and I don't know what happened to not get me an origin.

**Comment by AlienPebbles** [comment]
How did you fix it??

**Comment by ChrysanthCow** [comment]
MC version?

**Comment by squimbo** [comment]
This occurs the first time a world is loaded after booting minecraft

**Comment by N1zyx3** [comment]
How to fix it?
