### ISSUE TITLE
action_on_block_use prevents interaction with block

### ISSUE THREAD

**Issue by Cynic1254** [EdwinMindcraft/origins-architectury#419]
The `action_on_block_use` power prevent's the block event from happening even though the `action_result` has been set to a value that should allow this (pass or success).

I tested the same file/datapack on origins fabric and the block event did happen there.

```json
{
    "type": "origins:action_on_block_use",
    "block_condition": {
        "type": "origins:block",
        "block": "minecraft:bell"
    },
    "block_action": {
        "type": "origins:execute_command",
        "command": "execute as @e[nbt={Age:0},distance=..32] run data modify entity @s InLove set value 600"
    },
    "action_result": "pass"
}
```
[breed.json](https://github.com/EdwinMindcraft/origins-architectury/files/14351729/breed.json)

observed result: bell does not ring (and some weird things happen with the currently help item)
expected result: The bell should be ringing

**Comment by ChrysanthCow** [comment]
This was a matter of us accidentally cancelling block interaction without the context that Origins Fabric has,
