### ISSUE TITLE
Possible Epic fight Compatibility?

### ISSUE THREAD

**Issue by SassyPro1** [EdwinMindcraft/origins-architectury#420]
As the title states, would it be possible to add compatibility with epic fight mod, specifically, the key binds used?

By default, for example when trying to use, the attack key bind from epic fight, any code does not work, and you will just attack.

**Comment by ChrysanthCow** [comment]
Hi, you are able to modify which keys are used through datapack. Origins itself isn't really supposed to be designed around having Epic Fight, so your best bet is to look at Epic Fight's keybind ids, and replace parts of powers with them. None of the base Origins really have a power tied to the attack key either, so this is potentially purely custom origins business which is out of our control.
