### ISSUE TITLE
Suspected Mod: Apoli            Description: Ticking entity

### ISSUE THREAD

**Issue by DanfeUran** [EdwinMindcraft/origins-architectury#425]
So when want start new wold it allways crash
[crash-2024-03-13_20.20.32-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14593497/crash-2024-03-13_20.20.32-server.txt)

**Comment by ChrysanthCow** [comment]
huh, weird. I'll get this sorted in a bit.

**Comment by ChrysanthCow** [comment]
Should be fixed in 1.10.0.7

**Comment by DanfeUran** [comment]
Thx just curious, what was problem?

**Comment by ChrysanthCow** [comment]
> Thx just curious, what was problem? 

A lack of a null check in the `replace_loot_table` power type logic.
