### ISSUE TITLE
damage_condition doesn't work

### ISSUE THREAD

**Issue by squimbo** [EdwinMindcraft/origins-architectury#426]
No matter what I do, I cannot get the damage_condition field of modify_damage_taken to work, even using the given examples on the wiki.
Here is my code. Without the condition it works fine.

```
{
    "type": "origins:modify_damage_taken",
    "name": "Example",
    "description": "Magic damage is doubled",
    "damage_condition": {
        "type": "origins:type",
        "damage_type": "minecraft:magic"
    },
    "modifier": {
        "operation": "multiply_base_multiplicative",
        "value": 1
    },
    "self_action": {
        "type": "origins:execute_command",
        "command": "execute as @s run tell @a hi"
    }
}
```
Log in case it's helpful (sorry about all the other mods)
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/14621933/latest.log)

**Comment by ChrysanthCow** [comment]
The `type` damage condition is not in origins 1.20.1.

**Comment by squimbo** [comment]
my bad- wiki defaults to version 11. I am dumb
