### ISSUE TITLE
After March 15th update getting Crashes related to "java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "this.lootTableId" is null"

### ISSUE THREAD

**Issue by Darkmega18** [EdwinMindcraft/origins-architectury#428]
I think something you (MerchantPug) rewrote in a recent version (1.7.1.4) after a different issue report isn't sitting well with a bunch of other stuff on 1.19.2 that I'm using. So it might've been a step back in some regards unforseen.

I'm getting so many crashes related to Mana and Artifice and eventually a veinmining moment (the topafter I removed it all related to: "java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "this.lootTableId" is null"
It seems to occur whenever mobs fight one another with MnA due to it's faction mobs having little fights off screen.
The Ore excavation issue also hit me with a crash related to the same kind of error. I only found out it was related to apoli eventually due to searching through debug logs and eventually installing "not enough crashes" which seems to be wise to the mod and where the crash ACTUALLY comes from.

Heres some example crashes I've had over the last couple days.
Currently, I'm using origins only to implement my "deaths door" mechanic into a recent testing pack (which you might recall from some of my other issues that had been troubleshooted). But otherwise everyones origin is defaulted to human.

_Mana and artifice and one Mii Alliance related call somewhere in there, I forget which one._
[crash-2024-03-17_13.05.39-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14625964/crash-2024-03-17_13.05.39-server.txt)
[crash-2024-03-17_12.45.10-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14625965/crash-2024-03-17_12.45.10-server.txt)
[crash-2024-03-15_19.38.13-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14625966/crash-2024-03-15_19.38.13-server.txt)
[crash-2024-03-15_15.33.45-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14625967/crash-2024-03-15_15.33.45-server.txt)
[crash-2024-03-15_15.29.55-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14625968/crash-2024-03-15_15.29.55-server.txt)
[crash-2024-03-15_15.20.40-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14625969/crash-2024-03-15_15.20.40-server.txt)

_ore excav related loot call after installing not enough crashes._
[crash-2024-03-17_13.21.46-server.txt](https://github.com/EdwinMindcraft/origins-architectury/files/14625963/crash-2024-03-17_13.21.46-server.txt) 

Theres also a crash that someone else posted before me on this issue here we both went to after our initial run ins with the bug due to what the stack traces pointed to. 

I can confirm they also have the most recent 1.19.2 origins version installed after reading their crash report to grab the modlist.
https://github.com/Mithion/Mana-And-Artifice/issues/730

I had smooth sailing before this update, so... I guess I'll do what I always do and backdate for a bit until you lemme know it should be good? Thanks.

**Comment by ChrysanthCow** [comment]
Ah, this is the same issue as #425. Will fix eventually.

**Comment by Darkmega18** [comment]
guess it's something you need to backport? the linked issue seems fixed already?

**Comment by ChrysanthCow** [comment]
yeah

**Comment by Amelia115** [comment]
getting a similar issue with ours, going to backdate and see if it works. ill get back yo ya

**Comment by ChrysanthCow** [comment]
Brought over the fix from 1.20.1, fixed!

**Comment by Darkmega18** [comment]
oh! spicy. thanks pug.
