### ISSUE TITLE
Missing layers fail save is not functioning upon rejoining

### ISSUE THREAD

**Issue by CyroxTM** [EdwinMindcraft/origins-architectury#43]
I have 3 layers, 2 are custom, 1 is the origins one
This is how the order goes:
The user picks the first custom layer, then the origins layer, then the second custom layer.
If the second (origins layer) or the third layers are no longer valid (missing ID or set to "origins:empty) upon rejoining the world/server they are given to repick the first layer, even tho they already have that, picking it shows in the logs:
`[Server thread/WARN] [io.gi.ap.or.Origins/]: Player  tried to choose origin for layer server:globals while having one already.`
(server:globals is the first layer)
On the original version (fabric) it correctly guides the user to repick the missing layers

**Comment by EdwinMindcraft** [comment]
Unfortunately, I'm not aware of how to fix that particular issue. see #24 for more information. Basically forge networking isn't the most stable when the player isn't connected yet, and I'm unaware of a way to make it do the things I want.
