### ISSUE TITLE
Random crashes because "this.lootTableId" is null

### ISSUE THREAD

**Issue by isajohoff** [EdwinMindcraft/origins-architectury#431]
Server with large amount of mods crashes (sometimes randomly during gametime, sometimes on startup) with a 
> java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "this.lootTableId" is null

error.

[crash report](https://github.com/EdwinMindcraft/origins-architectury/files/14829020/crash-2024-04-01_20.23.59-server.txt)

Removed only Origins and Origins: Classes, and the crashes stopped happening.

Thanks for your work! ^-^

**Comment by ChrysanthCow** [comment]
Downgrade Origins to the previous version, I have yet to release a fix for 1.19.2

**Comment by ChrysanthCow** [comment]
Duplicate of https://github.com/EdwinMindcraft/origins-architectury/issues/428

**Comment by ChrysanthCow** [comment]
Brought over the fix from 1.20.1, fixed!
