### ISSUE TITLE
[1.20][Forge] Incompatibility with Spice of Life Onion

### ISSUE THREAD

**Issue by CreativeMD** [EdwinMindcraft/origins-architectury#435]
Hey there,
I'm the author of Spice of Life Onion and someone has reported an issue with origins. My mod adds food bags, if you eat the bag it will consume an item it contains. Somehow this behavior does not work if origins is installed (https://github.com/CreativeMD/Spice-of-Life-Onion/issues/5). Do you have an idea what could possibly cause this issue?

In Regards
CreativeMD

**Comment by ChrysanthCow** [comment]
1. Does this work with an origin without a dietary restriction (Vegetarian on Avian, Carnivore on Arachnid)
2. You'll want to add this item to the `origins:ignore_diet` tag.
3. If you wish to go the extra mile for Origins compat, you might want to make sure that the item is edible by checking prevent item use powers. An example of how you can do this is here.
https://github.com/EdwinMindcraft/apoli/blob/1.18.x/1.18.2/src/main/java/io/github/edwinmindcraft/apoli/common/ApoliPowerEventHandler.java#L366

Sorry for the late response, I've been trying to pace myself with maintaining this mod.

**Comment by CreativeMD** [comment]
Hey thanks for taking care. Unfortunately adding the item to the `origins:ignore_diet` tag did not help (or I did something wrong, I have never added something to another mod's tags). Commit can be found here: https://github.com/CreativeMD/Spice-of-Life-Onion/commit/ad656c73572b1170ea5114a9104cfea6ea8e64c2

**Comment by ChrysanthCow** [comment]
> Hey thanks for taking care. Unfortunately adding the item to the `origins:ignore_diet` tag did not help (or I did something wrong, I have never added something to another mod's tags). Commit can be found here: [CreativeMD/Spice-of-Life-Onion@ad656c7](https://github.com/CreativeMD/Spice-of-Life-Onion/commit/ad656c73572b1170ea5114a9104cfea6ea8e64c2)

I must've got the tag wrong.

**Comment by ChrysanthCow** [comment]
Huh weird, it is the correct tag...

**Comment by ChrysanthCow** [comment]
Ill test this when im next on pc.

**Comment by ChrysanthCow** [comment]
@CreativeMD Hi, you'll need to invert your `isUsagePrevented` check in OriginsManager. I'll make a PR on your end to fix this.

**Comment by ChrysanthCow** [comment]
https://github.com/CreativeMD/Spice-of-Life-Onion/pull/21

I have tested this with Origins Forge, and it should now work as intended.

**Comment by CreativeMD** [comment]
Oh wow, makes sense. Have not thought about it. Thank you so much for looking into it and taken care! New version is uploaded. Again thank you, was nice working with you!
