### ISSUE TITLE
using the "infinite" keyword in a /effect command on feline origin does not work

### ISSUE THREAD

**Issue by ABSOLUTEMAX123** [EdwinMindcraft/origins-architectury#438]
read the title. using /effect give @p minecraft:strength infinite and using the feline origin does not negate the weak arms effect.

**Comment by ChrysanthCow** [comment]
This was something fixed in a later version of Origins Fabric, im unsure if i can specifically change the value here due to disparity with 1.20.1

**Comment by ChrysanthCow** [comment]
I'll probably fix this because it shouldn't break anything, thanks for the report.
