### ISSUE TITLE
[1.20.1] `exposed_to_sun` is actually checking the z+1 position

### ISSUE THREAD

**Issue by LTCatt** [EdwinMindcraft/origins-architectury#439]
![image](https://github.com/apace100/origins-fabric/assets/40348278/0c04a575-e3d2-49a0-8a32-34166af64479)
![image](https://github.com/apace100/origins-fabric/assets/40348278/2b045bbe-4520-4682-b844-eb0e0af9d461)

Tests fine in Origins (Fabric)
Version: 1.20.1-1.10.0.1

**Comment by ChrysanthCow** [comment]
Thanks for this report. Ill fix it when i can.

**Comment by LTCatt** [comment]
It relates to the negative coordinates. At (100, 100) the detection is perfectly fine, but at (-100, -100) it is detecting (-99, -99).
I'm sorry, but is there an expected time for this to be fixed? My players are already abusing this bug :/

**Comment by ChrysanthCow** [comment]
Expect a release in the first or second week of this month.

**Comment by ChrysanthCow** [comment]
Okay, I've gone in and fixed the issue.

The issue was that the conversion of the `exposed_to_sky` condition check did not use the block position of the entity, but rather the regular position, with dropped decimals.

So standing on -99.5 would result in checking -99, rather than -100.

**Comment by ChrysanthCow** [comment]
Will be fixed in Origins Forge 1.10.0.8
