### ISSUE TITLE
[1.20.1] `disable_regen` will consume the hunger value constantly

### ISSUE THREAD

**Issue by LTCatt** [EdwinMindcraft/origins-architectury#440]
After installing Apple Skin, it is clear that applying `{"type": "origins:disable_regen"}` does not cause a recovery, but it will consume the hunger value quickly, as if it were doing a normal recovery.
Testing in Origins (Fabric), it's not consumed.
Version: 1.20.1-1.10.0.1

**Comment by ChrysanthCow** [comment]
Hi, I can't reproduce this with just Origins Forge, Caelus and AppleSkin (checked both client only and integrated server) alone. Could you please do a binary search on your mods and see if any are interferring with this logic?

From the NeoForge discord:
> The **binary search** is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.
> 
> This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.
> 
> The procedure is simple:
> 1. Remove half of the existing things, and put them aside.
> 2. Run the program / game.
> 3. Does the issue still exist?
>     - If **YES**: Repeat from step 1 with the current things.
>     - IF **NO**: Swap out the current things with the ones set aside, and repeat from step 1.
> 4. Repeat this process until the problematic thing/s have been found.

**Comment by LTCatt** [comment]
idk why but i can't repoduce it too. maybe this could be closed. sorry for that.
