### ISSUE TITLE
Cross compatibility Issue with Armor points++

### ISSUE THREAD

**Issue by Darkmega18** [EdwinMindcraft/origins-architectury#441]
in my modpack due to the ability to gain extra health and the nice compact nature of armor points++ I've been using the mod.
in 1.19.2 1.7.1.3 armor bar and health features all seem to be functioning properly normal.
However when updating to 1.7.1.5 after you fixed that last issue for me I'm noticing that the armor bar is now somewhat broken, the health render has seemingly forced itself back to normal and my health numbers are like halfway up my screen in the middle of nowhere.

Were there some ui overrides/changes in 1.7.1.4 and such that could cause a mod that chances the health render etc like AP++ to break?

I do remember that such issues also occurred to me in a 1.20 test pack also. so it's not just a 1.19.2 related issue again.
so once more, I'm still kinda stuck in 1.7.1.3 unless I want to get annoyed by wrongly placed health widgets. :V

**Comment by ChrysanthCow** [comment]
Weird.

**Comment by Darkmega18** [comment]
indeed. any idea what's going on?

**Comment by ChrysanthCow** [comment]
Hi, I'm unable to replicate using just Origins Forge and AP++ could you send a screenshot as to what it looks like on your end, because it looks pretty normal to me (using AP++ 3.1.0)

**Comment by ChrysanthCow** [comment]
https://github.com/Cheos137/ArmorpointsPlusplus/issues/40
It could potentially be related to this? Please try updating AP++ to 3.1.0 and see if the issue still persists.

**Comment by Darkmega18** [comment]
I am already using 3.1.0, since thats latest available for 1.19.2 but I'll give it a quick go and show you a shot if it doesn't work.

**Comment by Darkmega18** [comment]
strange. it suddenly started working.
wonder if it was cause at one point I changed which textures it was using? since the mod has some texture packs you can switch between. But well, for whatever reason it seems to have fixed itself.
