### ISSUE TITLE
aternos server not launching due to unknown issue

### ISSUE THREAD

**Issue by GuiGuidu33** [EdwinMindcraft/origins-architectury#443]
Well i was using the currently last version of origins forge 1.20.1 for an aternos server and everytime it just didn't start at all. I tried with just origins and caelus API and it still showed the same result can someone help me ?
It might be an aternos issue though so sorry for causing here trouble if it is.

Here are the logs if needed : https://mclo.gs/8rbZXsJ

**Comment by ChrysanthCow** [comment]
Thanks, I'll get a fix out sometime soon. This is on our end.

**Comment by GuiGuidu33** [comment]
Oh ok thank you for the clarification ! I'll wait for that fix then.

**Comment by ChrysanthCow** [comment]
I already fixed it in 1.10.0.9

**Comment by GuiGuidu33** [comment]
Thank you ! It works flawlessly now !
