### ISSUE TITLE
Incompatible with Forgified Fabric?

### ISSUE THREAD

**Issue by Peacuch** [EdwinMindcraft/origins-architectury#450]
I've been creating a modpack with the Forgified Fabric, and the Sinytra Connector, and I've had some mild success with a few other mods, but for some reason Origins TOTALLY hates this setup. I'm sure it's got to do with the fact that Origins hijacks your game right after the world loads, but... I really am not a coder, so I have no idea what could be wrong with it.

I've tried using the Fabric Version of Origins, as well as some older versions because I thought since Forgified Fabric, and Sinytra Connector force you to use the old Forge version, that maybe that was why... but no luck. 

The crash report I get from Minecraft's Launcher is something like this:
The game crashed whilst rendering overlay
Error: java.lang.IllegalArgumentException: Failed to create model for minecraft:armor_stand
Exit Code: -1

Although interestingly enough, if I keep trying it the "armor_stand" gets replaced with other stuff like I got "husk", and "skeleton" a few times too. 

I guess this is a pretty insane ask, especially because everyone making this mod must be so busy as-is, but I really as excited to use Origins, and... now I'm realizing it won't work at all...

**Comment by Peacuch** [comment]
Correction, and apology, I wasn't using the Caelus API (Forge/NeoForge) in my pack, that's my bad. BUT I'm not going to delete this because Caelus API should have been added automatically with the CurseForge Launcher, and it wasn't. So maybe that helps someone out there with the same issue.

**Comment by ChrysanthCow** [comment]
I have now fixed the Caelus API dependency on CurseForge.
