### ISSUE TITLE
Origins forge conflicts with latest timeless and classic guns version

### ISSUE THREAD

**Issue by GeekyRaptor** [EdwinMindcraft/origins-architectury#453]
The two mods do not play nice together and my game crashes.
[latest.log](https://github.com/user-attachments/files/15810814/latest.log)

**Comment by ChrysanthCow** [comment]
ah, classic Redirect conflict.
Unfortunately, the other mod has been discontinued, and Origins Forge 1.18.2 has also been discontinued.
I also just don't think there's a good fix for this, because it seems to be more of an issue on their end.
