### ISSUE TITLE
Missing origins:random_teleport on 1.20.1-1.10.0.9

### ISSUE THREAD

**Issue by TheOdiumWitch** [EdwinMindcraft/origins-architectury#459]
![image](https://github.com/EdwinMindcraft/origins-architectury/assets/41388218/c5c898dc-7381-4815-ab31-2e6bfcc9b587)

[undying.json](https://github.com/user-attachments/files/15963283/undying.json)

As such, certain functionality available on fabric is inaccessible on forge.

**Comment by ChrysanthCow** [comment]
Hi, this content is not in the 1.20.1 version of Origins, thus we cannot reasonably add it to the 1.20.1 version of Origins Forge. Thanks for understanding.
