### ISSUE TITLE
Datapack causes internal server crash on world load.

### ISSUE THREAD

**Issue by AkkiTheGamerFox** [EdwinMindcraft/origins-architectury#469]
Attempting to load a world with the datapack selected causes the internal server to crash error log is screenshotted below, and here's a drive link with the pack in question, for debugging:
Tested with the Better MC mod pack, but I currently have no reason to suspect mod conflicts.
https://drive.google.com/file/d/12SjDmyPnn12CbmPXG51oNdL8yxvBNZDp/view?usp=sharing
![Minecraft game output 7_31_2024 3_55_01 PM](https://github.com/user-attachments/assets/f20eeb34-08c2-4511-ba01-54d0a28135f4)
![Minecraft_ Forge Loading  7_31_2024 3_55_09 PM](https://github.com/user-attachments/assets/d6204611-9ee6-40fe-b65a-d00900c41d0b)

**Comment by ChrysanthCow** [comment]
Hi, your `starglade:aku/dj_grounded` datapack is broken.
Ticking related things (such as the `interval` field in this case) should never be set to 0, as the game will crash when dividing by 0.
Set it to 1 and it should work.

**Comment by AkkiTheGamerFox** [comment]
> Hi, your `starglade:aku/dj_grounded` datapack is broken. Ticking related things (such as the `interval` field in this case) should never be set to 0, as the game will crash when dividing by 0. Set it to 1 and it should work.

Ah, understood, will forward this to the pack dev!
