### ISSUE TITLE
1.16.5 (Using latest version of origins forge port) Some powers aren't being registered in this datapack, every other datapack and origin works even in my survival world so it's not mihost interfering with it

### ISSUE THREAD

**Issue by ThatTopGamer** [EdwinMindcraft/origins-architectury#49]
[upgraded_1.4.zip](https://github.com/EdwinMindcraft/origins-architectury/files/6888993/upgraded_1.4.zip)
[ERROR] There was a problem reading power file upgraded:blastling_explode_fix (skipping): JsonSyntaxException: JsonSyntaxException: JSON requires field: conditions

[ERROR] There was a problem reading power file upgraded:prey (skipping): JsonSyntaxException: EntityCondition json requires "type" identifier.
![errorlogfororigins](https://user-images.githubusercontent.com/88057070/127234058-57263f4a-82d1-4a72-a026-7aebd8ce6f0c.jpg)

**Comment by ThatTopGamer** [comment]
I forgot to put logs here, sorry.
[2021-07-27-1.log.zip](https://github.com/EdwinMindcraft/origins-architectury/files/6889321/2021-07-27-1.log.zip)

**Comment by EdwinMindcraft** [comment]
As it says on the tin. Your datapack is broken.
