### ISSUE TITLE
Missing power and resource commands?

### ISSUE THREAD

**Issue by Darkmega18** [EdwinMindcraft/origins-architectury#52]
basically, I saw these:
https://origins.readthedocs.io/en/latest/misc/commands/

tried to use power, cause I saw a video showing someone using it on a mob, and I wanted to try science. but science failed when game is telling me the command doesn't exist or is wrong. :<

**Comment by EdwinMindcraft** [comment]
Power was introduced in 1.17 with apoli which allows the player to have powers without having an origin. There's no such command in 1.16.5.

**Comment by Darkmega18** [comment]
ah, I see. no desire or ability to port said functionality to what you have already or does it require capability you can't use?

**Comment by EdwinMindcraft** [comment]
Origins 1.17 is now 3 mods: Calio, Apoli and Origins.
Unfortunately for me, applying this in 1.16 means breaking the currently designed API, which means addons will be broken. This is why mods usually provide stable APIs, which Origins didn't do, so sweeping changes cannot be implemented right now.

**Comment by Darkmega18** [comment]
oh, well thats whack. :V
