### ISSUE TITLE
Datapacked origins will not be properly loaded if loaded through Global Data and Resource Packs mod

### ISSUE THREAD

**Issue by Kaleidio** [EdwinMindcraft/origins-architectury#53]
No idea if Yung's Paxi is working.  But this behaviour results in all origins retaining their defaults, and no new origins being registered.  No idea if the datapack loads through normal Resource Pack folder, but here's a zip of my datapack just in case

[defaults.zip](https://github.com/EdwinMindcraft/origins-architectury/files/7022054/defaults.zip)
this pack contains other mods data and not sure if it will load without them (but it should anyway)

There is nothing in the log claiming any malformed jsons.

I assume this is simply a loading order issue.

mc 1.16.5
forge 36.2.0
origins 0.7.3.9
global data and resource packs 1.7.4

**Comment by EdwinMindcraft** [comment]
Try increasing order in your origins and set replace: true in your layer. It might just be that Global Data and Resourcepacks is loading it's packs before origins'.
If it doesn't work I'll try to track down the issue, but I don't have much in terms of ideas of what it could be right now.

**Comment by Kaleidio** [comment]
I know by the way of the logs that it's definitely loading the datapack before origins even initializes.  Global Data and Resource packs expects that the data folder of every mod be loaded 1. in the expected vanilla location with the same default json reader system and 2. on mod init as is expected in the forge way.

when reading the log, global data and resource packs finished loading the pack nearly 700 lines before I saw origins say "origins initializing"

I will see if I can do the tweaks you mentioned and will tell you the result in a few minutes.

**Comment by Kaleidio** [comment]
Set replace to true.  Set order to 2.  still nothing.  I assume the failure to order properly is still occurring.

**Comment by Kaleidio** [comment]
https://github.com/DarkRoleplay/Global-Data-and-Resourcepacks/tree/master/src/main/java/net/dark_roleplay/drpglobaldatapack

here's there sourcecode for you so you can take a look at how they're doing the datapack system.  it's a very very small mod

**Comment by Kaleidio** [comment]
Just tested and can confirm that Paxi also loads before your mod does.

why are you loading data so late might I ask?

**Comment by Kaleidio** [comment]
just tested and no, it's broken with Paxi too

any recommended values for order?  I'm not sure I will be able to fix this on my end, you may have to actually rewrite your datapacking system to be more vanilla-forge system compatible.

**Comment by EdwinMindcraft** [comment]
Nah, if `order` & `replace` didn't work it's a problem on my end.

I just need to find the source of the issue.

**Comment by EdwinMindcraft** [comment]
Nevermind I'm dumb.
Just put `"loading_order": 1` in the files you've changed.
Example: arachnid.json
```json
{
  "loading_priority": 1,
	"powers": [
		"origins:climbing",
		"origins:master_of_webs",
		"origins:arthropod"
	],
	"icon": {
		"item": "minecraft:cobweb"
	},
	"order": 1,
	"impact": 1
}```
This fixes it with paxi.
Also you don't actually need all of origins data in your pack, but I'm guessing you're still making changes.

**Comment by Kaleidio** [comment]
ah alright.

and yes I have at least one change for every origin.  I even replaced Human with Super Human in a version you haven't seen yet.

thanks

**Comment by Kaleidio** [comment]
is it loading order or loading priority?  I've just came back to check this and saw
