### ISSUE TITLE
Re #53; provided solution did not solve the order loading mishap

### ISSUE THREAD

**Issue by Kaleidio** [EdwinMindcraft/origins-architectury#54]
here's the newest version of my datapack.  unzip before loading.

[KBPData.zip](https://github.com/EdwinMindcraft/origins-architectury/files/7025767/KBPData.zip)

absolutely none of the origins get modified on world start.  it's really starting to bug me.

did you mean to say "loading_order" or "loading_priority"?  you gave me conflicting information

**Comment by EdwinMindcraft** [comment]
loading_priority, I'm a derp.
Also you don't actually need to open a new issue. I get notifications from closed issues too.

**Comment by Kaleidio** [comment]
ah alright. I'll test again and see if it fixed.

some devs unfollow threads that they close so I had to make sure.

**Comment by Kaleidio** [comment]
yes, it's fixed.  thank you!
