### ISSUE TITLE
Phantom's Revamp of Null's Titan Shifter Pack V0.3.0 not working properly

### ISSUE THREAD

**Issue by Z4MU** [EdwinMindcraft/origins-architectury#56]
i dont know if its a bug but when i try to tranform into a titan my character stays the same size not tirning into a titan

**Comment by EdwinMindcraft** [comment]
Did you install [pehkui](https://www.curseforge.com/minecraft/mc-mods/pehkui/files/3419504)?

**Comment by Z4MU** [comment]
yes version 2.3.0

**Comment by EdwinMindcraft** [comment]
I can't find the data pack anywhere. Make sure it is designed for 1.16.5 as origins fabric is out for 1.17, and it has some new capabilities that aren't implemented in 1.16.5.

**Comment by Z4MU** [comment]
ok i´ll check that thcks
