### ISSUE TITLE
Hoe Damage Datapack not working

### ISSUE THREAD

**Issue by hakasapl** [EdwinMindcraft/origins-architectury#58]
Hi,

I'm working on a custom power which would give the player more damage with hoes. Here's what I have:

```
{
  "type": "origins:modify_damage_dealt",
  "damage_condition": {
    "type": "origins:using_item",
    "item_condition": {
      "type": "origins:ingredient",
      "ingredient": {
        "tag": "forge:tools/hoes"
      }
    }
  },
  "modifier": {
    "operation": "addition",
    "value": 8.0
  }
}
```

Do forge tags not work with origins:forge? This power is never even loaded. The log shows that the origin is requesting an unregistered power (the power above). Everything is spelled correctly and the other powers I have made work fine. Just this one has an issue.

Any help would be great, I'd be happy to give more info on request.

**Comment by EdwinMindcraft** [comment]
Currently, using_item is limited to items that have use animations, such as food or potions.
Items are unsupported.

**Comment by hakasapl** [comment]
Thanks for the info. Is there any other supported way to increase damage with specific tools?

**Comment by EdwinMindcraft** [comment]
[Equipped Item](https://origins.readthedocs.io/en/latest/entity_conditions/equipped_item/) might do the trick.
You can specify `"equipment_slot": "mainhand"`

**Comment by hakasapl** [comment]
That did it, thank you!
