### ISSUE TITLE
Unable to Assign "origins:creative_flight" power to custom Origin through Datapack

### ISSUE THREAD

**Issue by Astrolegium** [EdwinMindcraft/origins-architectury#60]
When trying to create a custom race through a datapack that has the "Creative Flight" power ( [Wiki Documentation](https://origins.readthedocs.io/en/latest/power_types/creative_flight/) ) it does not appear on the powers list in-game, and does not grant the player the ability to fly. The following is the JSON entry that was attempted:

{
    "type": "origins:creative_flight"
}

As this power type does not have additional fields, if the containing JSON is added to the correct origin in the origins folder, it should be visible in the race select screen and allow the player to fly by double jumping, however it does not. Altering the power type to "origins:elytra_flight" with no other modifications works correctly (though does not have a display name or description as those fields were left out)

Any assistance is appreciated, and I am definitely willing to provide any needed documentation or screen shots. Thank you in advance.

**Comment by EdwinMindcraft** [comment]
Creative flight was introduced in 1.17. Origins forge is still 1.16
