### ISSUE TITLE
Config Options

### ISSUE THREAD

**Issue by SirOMGitsYOU** [EdwinMindcraft/origins-architectury#61]
Hi,

Would you be able to make it possible to disable certain origins via the config? I'm specifically wanting to disable Phantom due to it being slightly OP on a server

**Comment by EdwinMindcraft** [comment]
You can do this by using a layer with `replace` set to true.

**Comment by SirOMGitsYOU** [comment]
> You can do this by using a layer with `replace` set to true.

Could you clarify what you mean by this as I don't have a clue what you mean or how to action this?

**Comment by EdwinMindcraft** [comment]
Create a datapack with a custom layer without phantom:
```json
{
  "replace": true,
  "origins": [
    "origins:arachnid",
    "origins:avian",
    "origins:blazeborn",
    "origins:elytrian",
    "origins:enderian",
    "origins:feline",
    "origins:human",
    "origins:merling",
    "origins:shulk"
  ]
}
```

If you have any custom origins, you may need to add them here
