### ISSUE TITLE
[1.17.1] Crash on Launch

### ISSUE THREAD

**Issue by TheGreElucid** [EdwinMindcraft/origins-architectury#64]
When launching, The game never opens and gives Exit Code 0. 
![crash](https://user-images.githubusercontent.com/44938113/138457758-faf0d9f9-fc6a-439f-ba87-7e65442b4129.png)

**Comment by EdwinMindcraft** [comment]
Please attach your crash log. I can't debug if I don't know what went wrong.

**Comment by TheGreElucid** [comment]
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/7398082/latest.log)

**Comment by TheGreElucid** [comment]
Doesnt send a crash log so that is the main log

**Comment by EdwinMindcraft** [comment]
This should be fixed with the 1.0.4.1 versions of origins and apoli. You can find them in the same place.
