### ISSUE TITLE
[1.17.1] Exit code 1 still...

### ISSUE THREAD

**Issue by TheGreElucid** [EdwinMindcraft/origins-architectury#65]
Hate to reopen the the same issue, but here we are. Apon updating with your new jars I still get exit code 0 when trying to launch. Below is the latest log of trying to launch. I will also provide a screenshot of the mods folder
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/7402023/latest.log)
![fix](https://user-images.githubusercontent.com/44938113/138537364-8bd08d5d-bd71-43d5-969d-db255d8563a1.png)
.

**Comment by EdwinMindcraft** [comment]
This time I actually tested in a proper env, it should be fixed.
