### ISSUE TITLE
Feline crashes my game whenever I try to select and gives me an exit code that doesn't exist anywhere on the internet(Exit Code -1)

### ISSUE THREAD

**Issue by Katgirl217** [EdwinMindcraft/origins-architectury#71]
Every other Origin works fine(Shulk and Phantom don't have the hunger debuffs though, which I really liked since it made it harder) but the feline just slaps me in the face and crashes Minecraft whenever I load a new world and select it as my origin. Then I get stuck with exit code -1 and I literally can't find anything on it, on Google to help fix it. I can only start a new world and pick a different Origin.

**Comment by Katgirl217** [comment]
Now the powers have stopped working on every origin

**Comment by Katgirl217** [comment]
Scratch that, now only the Shulk's power is working

**Comment by Katgirl217** [comment]
It appears that none of the origin's powers work except the Shulk and Elytrian. Yes I switched both power keys in controls multiple times

**Comment by DarkSoulMastery** [comment]
I also have this same issue on 1.17.1

**Comment by EdwinMindcraft** [comment]
Exit code -1 is just minecraft's way of saying the game crashed and a report was produced.
I'll try to look into it as soon as I get the chance.
