### ISSUE TITLE
1.17.1 crashes server

### ISSUE THREAD

**Issue by Ian1141** [EdwinMindcraft/origins-architectury#76]
The 1.17 version just crashes on a server, but works fine client side.

**Comment by Ian1141** [comment]
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/7533521/latest.log)

**Comment by EdwinMindcraft** [comment]
Server can now boot, no tests were made in actual play.

**Comment by Ian1141** [comment]
This fixed the issue
