### ISSUE TITLE
1.17.1 game wont open and crashes

### ISSUE THREAD

**Issue by Inonedn** [EdwinMindcraft/origins-architectury#77]
[debug.log](https://github.com/EdwinMindcraft/origins-architectury/files/7534787/debug.log)
[latest.log](https://github.com/EdwinMindcraft/origins-architectury/files/7534788/latest.log)

**Comment by EdwinMindcraft** [comment]
You should remove Apoli and Calio as those mods are contained in the origins unified jar you currently have installed.

**Comment by DarkSoulMastery** [comment]
Optifine cannot be played with origins forge because of https://github.com/EdwinMindcraft/origins-architectury/issues/69

**Comment by Inonedn** [comment]
thank you. It fixed the problem
