### ISSUE TITLE
Night vision on feline keeps flickering

### ISSUE THREAD

**Issue by ghost** [EdwinMindcraft/origins-architectury#82]
I have this server on Aternos with origins and some other mods and I picked feline, and the night vision is spazzing out like hell.
I didn't know a side-effect to picking feline was having seizures every time night comes :/
Anyways I suspect it might be that the timer on the night vision is kept under 10 secs and the warning flicker at the end of night vision is stacking.

**Comment by DarkSoulMastery** [comment]
This happens when it's raining at sunset

**Comment by ghost** [comment]
> This happens when it's raining at sunset

no, it always happens when it's outside and when either in a cave or outside
and also it only seems to happen on 1.17 ver

**Comment by DarkSoulMastery** [comment]
This can also happen in the sky

**Comment by ghost** [comment]
> This can also happen in the sky

yep, that's what I mean when I said when it's nighttime, corrected the comment.
I wonder when the devs are going to see this?

**Comment by EdwinMindcraft** [comment]
This is now fixed.
