### ISSUE TITLE
1.17.1 - Elytrian Origin - Armor is Broken

### ISSUE THREAD

**Issue by REODefSTYX** [EdwinMindcraft/origins-architectury#83]
Instead of being able to use Leather, Chainmail and Gold armor only (as how the mod lists it), those 3 and also Iron armor are un-equippable. Additionally, you are able to equip diamond and netherite armor sets. 

Quite obviously, this is broken on many levels, but it also makes the beginning parts of the game really challenging
I've included a video showing this in action. I don't have any audio or on-screen prompts showing this, but I click 3-6 time on the helmet slot for each of the helmets.

https://user-images.githubusercontent.com/94886674/142974856-88915b46-0145-48eb-80be-c6d20813354c.mp4

Also, I tested this with no other mods installed and the issue was still there. So no compatibility problems as far as I'm aware.

**Comment by tovc** [comment]
`{
  "type": "origins:restrict_armor",
  "head": {
    "type": "origins:armor_value",
    "comparison": ">",
    "compare_to": 2
  },
  "chest": {
    "type": "origins:armor_value",
    "comparison": ">",
    "compare_to": 5
  },
  "legs": {
    "type": "origins:armor_value",
    "comparison": ">",
    "compare_to": 4
  },
  "feet": {
    "type": "origins:armor_value",
    "comparison": ">",
    "compare_to": 1
  }
}`

the comparison operators are "greater than", rather than "less than"
