### ISSUE TITLE
[1.16.5 Feature Request]  Config for Foods

### ISSUE THREAD

**Issue by Reshy** [EdwinMindcraft/origins-architectury#84]
Hello, I wanted to ask since it's not currently included in the configs from what I could find, but is it possible to include an option to specifically whitelist or blacklist certain foods based on the carnivore/herbivore origins?  Modded foods aren't catagorized correctly and being able to go in and manually set them would be appreciated.

**Comment by mosharky** [comment]
There is already a way, just not through a config file. You have to add items to the `origins:meat` tag, which is every edible food for a carnivore, and obviously inedible for vegetarians. There's the `origins:ignore_diet` tag, which is a list of all foods that ignore an Origin's diet (the list is empty by default). You can easily do this using a datapack, or KubeJS, or CraftTweaker. 

You can also use JEI to search for the items in those tags. If you search for "$meat", you can see every item in the `origins:meat` tag.

**Comment by EdwinMindcraft** [comment]
Do as stated above, if you need to load a datapack without adding it manually, use [Paxi](https://www.curseforge.com/minecraft/mc-mods/paxi) or something similar.
