### ISSUE TITLE
Unable to right click when being a shulk

### ISSUE THREAD

**Issue by TurtleCoder15** [EdwinMindcraft/origins-architectury#85]
I am unable to right click when I am a shulk, but when I switch my origin I am able to right click once again.

**Comment by mosharky** [comment]
right click in what way?

**Comment by TurtleCoder15** [comment]
Right Click as in placing blocks, using bows, placing water from buckets, and using shields (intentional). The only thing I have been able to do is eat food.

**Comment by Frostbite1105** [comment]
I have the same problem :/

**Comment by DarkSoulMastery** [comment]
I have this same problem on 1.17.1
